MODULE SalePurchaseManufacturingPrice;

REQUIRE SaleManufacturingPrice, PurchaseManufacturingPrice, SalePurchaseInvoice, PricingSalePurchase;

PRIORITY Sale;

//----------------------------------------------------------------------------//

overPurchasePricingPriceUserInvoiceDetail(detail) += Sale.manufacturingPriceUserInvoiceDetail(detail);

Purchase.showManufacturingPriceInvoice(invoice) += showManufacturingPriceInvoice(invoicePurchaseInvoice(invoice));
Purchase.manufacturingPriceInvoiceDetail(invoiceDetail) += manufacturingPriceInvoiceDetail(invoiceDetailPurchaseInvoiceDetail(invoiceDetail));
Purchase.manufacturingSumInvoiceDetail(invoiceDetail) += manufacturingSumInvoiceDetail(invoiceDetailPurchaseInvoiceDetail(invoiceDetail));

overFillInvoiceUserInvoiceInvoice (sd, id) += ACTION SET Purchase.showManufacturingPriceUserInvoice (sd) <- showManufacturingPriceInvoice(id);
overFillInvoiceUserInvoiceDetailInvoiceDetail (sd, id) += ACTION SET Purchase.manufacturingPriceUserInvoiceDetail (sd) <- manufacturingPriceInvoiceDetail(id);
