MODULE PurchaseReturnOrder;

REQUIRE Order, PurchaseShipment, PurchaseOperation, PurchasePack;

PRIORITY Purchase, Operation;

NAMESPACE PurchaseReturn;

@defineOrder(' (закупка-возврат)', customer, customerStock, Purchase, showPurchasePack, 'Отображать упаковку');

@defineOrderStockDestination(customerStock, supplierStock);

@defineNumeratedObjectDefaultPrefix(userOrder, 'Нумератор для заказов (закупка-возврат)', 'ВЗ', purchaseReturn);

//----------------------------------------------- Операции -----------------------------------------------------//

@defineDocumentOperation(order, o);
@defineDocumentOperationPriceListType(userOrder);
@defineDocumentOperationLegalEntity(userOrder, supplier, 'Поставщик');
@defineDocumentOperationLegalEntity(userOrder, customer, 'Покупатель');

//------------------------------ Ограничение на выбор контрагентов -----------------------------//

CONSTRAINT supplierUserOrder(userOrder) AND NOT isSupplierLegalEntity(supplierUserOrder(userOrder))
    CHECKED BY supplierUserOrder MESSAGE 'Для заказа выбрано в качестве поставщика организация, не являющаяся поставщиком';
CONSTRAINT customerUserOrder(userOrder) AND NOT isCompanyLegalEntity(customerUserOrder(userOrder))
    CHECKED BY customerUserOrder MESSAGE 'Для заказа выбрано в качестве покупателя организация, не являющаяся компанией';

//------------------------------ Автоматическое проставление свойств -----------------------------//

supplierUserOrder(userOrder) <- defaultSupplierEmployee(currentUser()) IF countAccessSupplierEmployee (currentUser()) == 1
    WHEN ASSIGNED(userOrder IS userOrder);
customerUserOrder(userOrder) <- defaultCompanyEmployee(currentUser()) IF countAccessCompanyEmployee (currentUser()) == 1
    WHEN ASSIGNED(userOrder IS userOrder);

supplierStockUserOrder(userOrder) <- defaultStockEmployeeLegalEntity(currentUser(), supplierUserOrder(userOrder))
    IF countAccessStockEmployeeLegalEntity (currentUser(), supplierUserOrder(userOrder)) == 1
        WHEN CHANGED(supplierUserOrder(userOrder));
customerStockUserOrder(userOrder) <- defaultStockEmployeeLegalEntity(currentUser(), customerUserOrder(userOrder))
    IF countAccessStockEmployeeLegalEntity (currentUser(), customerUserOrder(userOrder)) == 1
        WHEN CHANGED(customerUserOrder(userOrder));

//------------------------------ Ввод в упаковках -----------------------------//

@defineDocumentPackSkuStock(userOrder, sku, customerStock, Purchase);
@extendFormDocumentPackSkuStockCustom(userOrder, userOrder, o, customerStock, showPurchasePack, Purchase);

overChangeQuantityValueSkuUserOrderDetail(detail) += ACTION (detail) {
    IF  packBarcodeSku(skuUserOrderDetail(detail)) THEN {

        SET quantityPackUserOrderDetail(detail) <- quantityUserOrderDetail(detail)/amountPackUserOrderDetail(detail);
    }
}

//------------------------------ Расширение формы -----------------------------//

// Фильтры
inAssortmentSkuStockUserOrder (sku, stock, userOrder) =
    companyLedgerPriceListTypeSkuStockDateTime(ledgerPriceListTypePriceListType(priceListTypeUserOrderSku(userOrder, sku)),
                                               sku, stock, dateTimeUserOrder(userOrder)) == supplierUserOrder(userOrder);

inUserOrderSku (userOrder, sku)= inSupplierSku(supplierUserOrder(userOrder), sku);
EXTEND FORM userOrder

    FILTERGROUP filter
        FILTER 'С остатком ' 'F10' currentBalanceSkuStock(s, st) DEFAULT
        FILTER 'В заказе ' 'F9' quantitySkuUserOrderCustomerStock(s, o, st)

   FILTERGROUP filter1
        FILTER 'С поступлением' 'F8' inUserOrderSku(o, s)
        FILTER 'В ассортименте' 'F7' inAssortmentSkuStockUserOrder(s, st, o) DEFAULT
;

// Резервы
@extendFormDocumentOrderLedgerStock(userOrder, userOrder, o);

//--------------------- Проводим по регистру резерва ------------------//
@implementPurchaseOrderLedger(order, sku, shipmentDateTime, customerStock, supplier);


NAVIGATOR {
    purchaseReturnNavigator {
        ADD orders;
    }
}
