name: ${docker.compose.projectName}

services:
  db:
    image: postgres:16
    volumes:
      - ./docker-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=11111

  logics:
    image: ${docker.image.fullName}
    depends_on:
      - db
    volumes:
      - ./docker-server:/lsfusion
    environment:
      - DB_SERVER=db
      - DB_PASSWORD=11111

  client:
    image: lsfusion/client:5.2-SNAPSHOT
    depends_on:
      - logics
    volumes:
      - ./docker-client-conf:/usr/local/tomcat/conf/Catalina
    ports:
      - "8080:8080"
    environment:
      - APP_SERVER=logics