MODULE Service;

REQUIRE System, Reflection;

NAMESPACE Service;

checkAggregationsAction 'Проверить аггрегации' = ACTION CUSTOM 'platform.server.logics.service.CheckAggregationsActionProperty';
recalculateAction 'Пересчитать аггрегации' = ACTION CUSTOM 'platform.server.logics.service.RecalculateActionProperty';
recalculateFollowsAction 'Пересчитать следствия' = ACTION CUSTOM 'platform.server.logics.service.RecalculateFollowsActionProperty';
analyzeDBAction 'Анализ БД' = ACTION CUSTOM 'platform.server.logics.service.AnalyzeDBActionProperty';
packAction 'Упаковать таблицы' = ACTION CUSTOM 'platform.server.logics.service.PackActionProperty';
serviceDBAction 'Обслуживание БД' = ACTION CUSTOM 'platform.server.logics.service.ServiceDBActionProperty';
getVMInfo 'Данные виртуальной машины' = ACTION CUSTOM 'platform.server.logics.service.GetVMInfoActionProperty';

restartServerAction 'Остановить сервер' = ACTION CUSTOM 'platform.server.logics.service.RestartActionProperty';
runGarbageCollector 'Запустить сборщик мусора' = ACTION CUSTOM 'platform.server.logics.service.GarbageCollectorActionProperty';
cancelRestartServerAction 'Отменить остановку сервера' = ACTION CUSTOM 'platform.server.logics.service.CancelRestartActionProperty';
isNotServerRestarting () = TRUE AND NOT isServerRestarting();

FORM admin 'Администрирование'
    PROPERTIES() currentDate, defaultBackgroundColor, defaultForegroundColor, restartServerAction SHOWIF isNotServerRestarting(),
                 cancelRestartServerAction SHOWIF isServerRestarting(), checkAggregationsAction, recalculateAction,
                 recalculateFollowsAction, packAction, analyzeDBAction, serviceDBAction,
                 runGarbageCollector, getVMInfo
;

NAVIGATOR {
    configuration {
        ADD Service.admin;
    }
}

