MODULE PurchaseCreditNote;

REQUIRE CreditNote, PurchaseShipment;

NAMESPACE Purchase;


//----------------------------------------------- Акт ---------------------------------------------------//

@defineCreditNote(' (закупка)', customerStock);

CONSTRAINT supplierUserCreditNote(userCreditNote) AND NOT isSupplierLegalEntity(supplierUserCreditNote(userCreditNote))
    CHECKED BY supplierUserCreditNote MESSAGE 'Для акта расхождения выбрано в качестве поставщика организация, не являющаяся поставщиком';
CONSTRAINT customerUserCreditNote(userCreditNote) AND NOT isCompanyLegalEntity(customerUserCreditNote(userCreditNote))
    CHECKED BY customerUserCreditNote MESSAGE 'Для акта расхождения выбрано в качестве покупателя организация, не являющаяся компанией';

NAVIGATOR {
    purchasePurchaseNavigator {
        ADD creditNotes;
    }
}