MODULE DimensionBank;

REQUIRE Dimension, Bank;

//-- Bank
EXTEND CLASS Bank : Dimension;
EXTEND CLASS DimensionType {
    bank 'Банк'
}
nameDimension (dimension) += name(dimension) IF dimension IS Bank;
dimensionTypeDimension (dimension) += DimensionType.bank WHEN dimension IS Bank;

//-- Account
EXTEND CLASS Bank.Account : Dimension;
EXTEND CLASS DimensionType {
    account 'Счет'
}
nameDimension (dimension) += numberAccount(dimension);
dimensionTypeDimension (dimension) += DimensionType.account WHEN dimension IS Bank.Account;

