MODULE DimensionTax;

REQUIRE Dimension, Tax;

EXTEND CLASS Range : Dimension;
EXTEND CLASS DimensionType {
    range 'Шкала'
}
nameDimension (dimension) += [FORMULA STRING[255]  ' CAST($1 AS TEXT) || \', шкала № \' || CAST($2 AS TEXT) || \', тек.ставка\' || \' ( \' || CAST($3 AS TEXT)|| \')\''](
    staticCaption(taxRange(dimension)), numberRange(dimension), valueCurrentRateRange(dimension));
dimensionTypeDimension (dimension) += DimensionType.range WHEN dimension IS Range;


