MODULE SaleReturnShipmentBin;

REQUIRE Bin, SaleReturnShipment, SaleShipmentBin;

NAMESPACE SaleReturn;

//---------------------------------Ячейка ----------------------------------//

@defineDocumentInterfaceDetailBin(shipment);
@extendFormInterfaceDetailBin(shipment, , quantity);
@deriveDocumentOperationProperty(UserShipment, showBin);

@defineInvoiceShipmentBin();
@deriveDocumentOperationProperty(UserInvoice, showBin);