MODULE SaleReturnManufacturingPrice;

REQUIRE SaleReturnInvoice, SaleManufacturingPrice;

NAMESPACE SaleReturn;

@defineDocumentInterfaceCreate (invoice, showManufacturingPrice, 'Цена изготовителя');

// -- Операция
@deriveDocumentOperationProperty(UserInvoice, showManufacturingPrice);

@defineDocumentInterfaceDetailPriceCustomPrefix(invoiceDetail, manufacturing, ' изготовителя');

overRecalculatedPriceUserInvoiceDetail(detail) += ACTION (detail) {
    SET SaleReturn.manufacturingPriceUserInvoiceDetail(detail) <- Sale.manufacturingPriceInvoiceDetail(invoiceDetailUserInvoiceDetail(detail));
}

@defineDocumentInterfaceDetailDataSumPrefix (invoice, manufacturing, ' изготовителя'); // объявляем сумму изготовителя
@deriveDocumentDetailSumPrefix(userInvoice, manufacturing, currency, quantity); // записываем сумму изготовителя

@defineDocumentInterfaceHeaderItemSum (invoice, manufacturing, manufacturing);

EXTEND FORM userInvoice
    PROPERTIES(i)  showManufacturingPriceUserInvoice
    PROPERTIES(d)  SHOWIF showManufacturingPriceUserInvoice(i) AFTER invoiceSumUserInvoiceDetail  manufacturingSumUserInvoiceDetail,
                   manufacturingPriceUserInvoiceDetail

;
EXTEND DESIGN userInvoice {
    headerExtraParams {
        NEW headerManufacturing {
            title = 'Цена изготовителя';
            ADD PROPERTY(showManufacturingPriceUserInvoice);
        }
    }
}

EXTEND FORM invoices
    PROPERTIES(i) READONLY showManufacturingPriceInvoice
    PROPERTIES(d) READONLY  SHOWIF showManufacturingPriceInvoice(i) AFTER invoiceSumInvoiceDetail manufacturingSumInvoiceDetail, manufacturingPriceInvoiceDetail
;

