MODULE Particulars;

REQUIRE System,
        MasterData,
        POS,
        RomanStock,
        PriceInterval,
        UserPriceChange,
        RetailPrice,
        Currency,
        RomanSales,
        RomanLogicsModule;

PRIORITY MasterData, Stock, RomanLogicsModule;

GROUP totalGroupSupplier 'Итого (поставщик)' : publicGroup;


balanceBSupplierDate 'Остаток на начало' (supplier, dateFrom) =  GROUP SUM balanceBArticleDate(article, dateFrom)
    BY supplierArticle(article), dateFrom;
balanceBBrandSupplierDate 'Остаток на начало' (brandSupplier, dateFrom) =  GROUP SUM balanceBArticleDate(article, dateFrom)
    BY brandSupplierArticle(article), dateFrom;
balanceBCategorySupplierDate 'Остаток на начало' (categorySupplier, dateFrom) =  GROUP SUM balanceBArticleDate(article, dateFrom)
    BY categorySupplierArticle(article), dateFrom;
balanceBSubCategorySupplierDate 'Остаток на начало' (subCategorySupplier, dateFrom) =  GROUP SUM balanceBArticleDate(article, dateFrom)
    BY subCategorySupplierArticle(article), dateFrom;
balanceBThemeSupplierDate 'Остаток на начало' (themeSupplier, dateFrom) =  GROUP SUM balanceBArticleDate(article, dateFrom)
    BY themeSupplierArticle(article), dateFrom;


quantityReceivedArticleDateFromTo 'Поступило за интервал' (article, dateFrom, dateTo) = (balanceAArticleDate(article, dateTo) AND dateFrom AS DATE) (-)
    (balanceBArticleDate(article, dateFrom) AND dateTo AS DATE) (+) quantitySoldArticleDateFromTo(article, dateFrom, dateTo);

quantityReceivedSupplierDateFromTo 'Поступило' (supplier, dateFrom, dateTo)= GROUP SUM quantityReceivedArticleDateFromTo(article, dateFrom, dateTo)
    BY supplierArticle(article), dateFrom, dateTo;
quantityReceivedBrandSupplierDateFromTo 'Поступило' (brandSupplier, dateFrom, dateTo)= GROUP SUM quantityReceivedArticleDateFromTo(article, dateFrom, dateTo)
    BY brandSupplierArticle(article), dateFrom, dateTo;
quantityReceivedCategorySupplierDateFromTo 'Поступило' (categorySupplier, dateFrom, dateTo)= GROUP SUM quantityReceivedArticleDateFromTo(article, dateFrom, dateTo)
    BY categorySupplierArticle(article), dateFrom, dateTo;
quantityReceivedSubCategorySupplierDateFromTo 'Поступило' (subCategorySupplier, dateFrom, dateTo)= GROUP SUM quantityReceivedArticleDateFromTo(article, dateFrom, dateTo)
    BY subCategorySupplierArticle(article), dateFrom, dateTo;
quantityReceivedThemeSupplierDateFromTo 'Поступило' (themeSupplier, dateFrom, dateTo)= GROUP SUM quantityReceivedArticleDateFromTo(article, dateFrom, dateTo)
    BY themeSupplierArticle(article), dateFrom, dateTo;

quantitySoldSupplierDateFromTo 'Продано за интервал (кол-во)' (supplier, dateFrom, dateTo) = GROUP SUM
    quantitySoldArticleDateFromTo(article, dateFrom, dateTo) BY supplierArticle(article), dateFrom, dateTo;
quantitySoldBrandSupplierDateFromTo 'Продано за интервал (кол-во)' (brandSupplier, dateFrom, dateTo) = GROUP SUM
    quantitySoldArticleDateFromTo(article, dateFrom, dateTo) BY brandSupplierArticle(article), dateFrom, dateTo;
quantitySoldCategorySupplierDateFromTo 'Продано за интервал (кол-во)' (categorySupplier, dateFrom, dateTo) = GROUP SUM
    quantitySoldArticleDateFromTo(article, dateFrom, dateTo) BY categorySupplierArticle(article), dateFrom, dateTo;
quantitySoldSubCategorySupplierDateFromTo 'Продано за интервал (кол-во)' (subCategorySupplier, dateFrom, dateTo) = GROUP SUM
    quantitySoldArticleDateFromTo(article, dateFrom, dateTo) BY subCategorySupplierArticle(article), dateFrom, dateTo;
quantitySoldThemeSupplierDateFromTo 'Продано за интервал (кол-во)' (themeSupplier, dateFrom, dateTo) = GROUP SUM
    quantitySoldArticleDateFromTo(article, dateFrom, dateTo) BY themeSupplierArticle(article), dateFrom, dateTo;



sumSoldSupplierDateFromTo 'Продано за интервал (сумма)' (supplier, dateFrom, dateTo) = GROUP SUM
    sumSoldArticleDateFromTo(article, dateFrom, dateTo) BY supplierArticle(article), dateFrom, dateTo;
sumSoldBrandSupplierDateFromTo 'Продано за интервал (сумма)' (brandSupplier, dateFrom, dateTo) = GROUP SUM
    sumSoldArticleDateFromTo(article, dateFrom, dateTo) BY brandSupplierArticle(article), dateFrom, dateTo;
sumSoldCategorySupplierDateFromTo 'Продано за интервал (сумма)' (categorySupplier, dateFrom, dateTo) = GROUP SUM
    sumSoldArticleDateFromTo(article, dateFrom, dateTo) BY categorySupplierArticle(article), dateFrom, dateTo;
sumSoldSubCategorySupplierDateFromTo 'Продано за интервал (сумма)' (subCategorySupplier, dateFrom, dateTo) = GROUP SUM
    sumSoldArticleDateFromTo(article, dateFrom, dateTo) BY subCategorySupplierArticle(article), dateFrom, dateTo;
sumSoldThemeSupplierDateFromTo 'Продано за интервал (сумма)' (themeSupplier, dateFrom, dateTo) = GROUP SUM
    sumSoldArticleDateFromTo(article, dateFrom, dateTo) BY themeSupplierArticle(article), dateFrom, dateTo;

balanceASupplierDate 'Остаток на конец' (supplier, dateTo)= GROUP SUM balanceAArticleDate(article, dateTo)
    BY supplierArticle(article), dateTo;
balanceABrandSupplierDate 'Остаток на конец' (brandSupplier, dateTo)= GROUP SUM balanceAArticleDate(article, dateTo)
    BY brandSupplierArticle(article), dateTo;
balanceACategorySupplierDate 'Остаток на конец' (categorySupplier, dateTo)= GROUP SUM balanceAArticleDate(article, dateTo)
    BY categorySupplierArticle(article), dateTo;
balanceASubCategorySupplierDate 'Остаток на конец' (subCategorySupplier, dateTo)= GROUP SUM balanceAArticleDate(article, dateTo)
    BY subCategorySupplierArticle(article), dateTo;
balanceAThemeSupplierDate 'Остаток на конец' (themeSupplier, dateTo)= GROUP SUM balanceAArticleDate(article, dateTo)
    BY themeSupplierArticle(article), dateTo;

percentBalanceReceivedArticleDateFromTo '%, остатка' (article, dateFrom, dateTo) = round2([X*100/Y](
    balanceAArticleDate(article, dateTo), quantityReceivedArticleDateFromTo(article, dateFrom, dateTo)));

percentBalanceReceivedSupplierDateFromTo '%, остатка' (supplier, dateFrom, dateTo) = round2([X*100/Y](
    balanceASupplierDate(supplier, dateTo), quantityReceivedSupplierDateFromTo(supplier, dateFrom, dateTo)));
percentBalanceReceivedBrandSupplierDateFromTo '%, остатка' (brandSupplier, dateFrom, dateTo) = round2([X*100/Y](
    balanceABrandSupplierDate(brandSupplier, dateTo), quantityReceivedBrandSupplierDateFromTo(brandSupplier, dateFrom, dateTo)));
percentBalanceReceivedCategorySupplierDateFromTo '%, остатка' (categorySupplier, dateFrom, dateTo) = round2([X*100/Y](
    balanceACategorySupplierDate(categorySupplier, dateTo), quantityReceivedCategorySupplierDateFromTo(categorySupplier, dateFrom, dateTo)));
percentBalanceReceivedSubCategorySupplierDateFromTo '%, остатка' (subCategorySupplier, dateFrom, dateTo) = round2([X*100/Y](
    balanceASubCategorySupplierDate(subCategorySupplier, dateTo), quantityReceivedSubCategorySupplierDateFromTo(subCategorySupplier, dateFrom, dateTo)));
percentBalanceReceivedThemeSupplierDateFromTo '%, остатка' (themeSupplier, dateFrom, dateTo) = round2([X*100/Y](
    balanceAThemeSupplierDate(themeSupplier, dateTo), quantityReceivedThemeSupplierDateFromTo(themeSupplier, dateFrom, dateTo)));

FORM salesArticle 'Продажи по группам'

    OBJECTS dates = (dFrom = DATE, dTo = DATE) FIXED PANEL
    PROPERTIES valFrom = OBJVALUE(dFrom), valTo = OBJVALUE(dTo)

    OBJECTS s=supplier FIXED PANEL
    PROPERTIES     SELECTOR nameSup = name(s)
    PROPERTIES     READONLY balanceBSupplierDate(s,dFrom), quantityReceivedSupplierDateFromTo(s,dFrom,dTo), quantitySoldSupplierDateFromTo(s,dFrom,dTo), balanceASupplierDate(s,dTo),
                   percentBalanceReceivedSupplierDateFromTo(s,dFrom,dTo), sumSoldSupplierDateFromTo(s,dFrom,dTo)

    OBJECTS b=brandSupplier
    PROPERTIES     READONLY nameBr = name(b), balanceBBrandSupplierDate(b,dFrom), quantityReceivedBrandSupplierDateFromTo(b,dFrom,dTo), quantitySoldBrandSupplierDateFromTo(b,dFrom,dTo), balanceABrandSupplierDate(b,dTo),
                   percentBalanceReceivedBrandSupplierDateFromTo(b,dFrom,dTo), sumSoldBrandSupplierDateFromTo(b,dFrom,dTo)

    OBJECTS c=categorySupplier
    PROPERTIES     READONLY nameCat = name(c), balanceBCategorySupplierDate(c,dFrom), quantityReceivedCategorySupplierDateFromTo(c,dFrom,dTo), quantitySoldCategorySupplierDateFromTo(c,dFrom,dTo), balanceACategorySupplierDate(c,dTo),
                   percentBalanceReceivedCategorySupplierDateFromTo(c,dFrom,dTo), sumSoldCategorySupplierDateFromTo(c,dFrom,dTo)

    OBJECTS sc=subCategorySupplier
    PROPERTIES     READONLY nameSubCat = name(sc), sidSubCategorySupplier(sc), balanceBSubCategorySupplierDate(sc,dFrom), quantityReceivedSubCategorySupplierDateFromTo(sc,dFrom,dTo), quantitySoldSubCategorySupplierDateFromTo(sc,dFrom,dTo), balanceASubCategorySupplierDate(sc,dTo),
                   percentBalanceReceivedSubCategorySupplierDateFromTo(sc,dFrom,dTo), sumSoldSubCategorySupplierDateFromTo(sc,dFrom,dTo)

    OBJECTS aa=article
    PROPERTIES (aa)READONLY sidArticle, nameSupplierArticle, nameBrandSupplierArticle, nameCategorySupplierArticle, nameSubCategorySupplierArticle

    PROPERTIES  READONLY balanceBArticleDate(aa,dFrom), quantityReceivedArticleDateFromTo(aa, dFrom, dTo), quantitySoldArticleDateFromTo(aa, dFrom, dTo),
                balanceAArticleDate(aa, dTo), percentBalanceReceivedArticleDateFromTo(aa, dFrom, dTo), sumSoldArticleDateFromTo(aa, dFrom, dTo)

    FILTERS  supplierBrandSupplier(b) == s,
             supplierCategorySupplier(c) == s,
             categorySupplierSubCategorySupplier(sc) == c

    FILTERGROUP filtersSold
        FILTER 'Артикул поставщика' 'F10' supplierArticle(aa) == s
        FILTER 'Артикул бренда' 'F9' brandSupplierArticle(aa) ==b


    FILTERGROUP filtersSold1
        FILTER 'Артикул группы' 'F8' categorySupplierArticle(aa) == c
        FILTER 'Артикул подгруппы' 'F7' subCategorySupplierArticle(aa) == sc

    FILTERGROUP filtersSoldArticle
        FILTER 'Артикул с движением' 'F11' quantityReceivedArticleDateFromTo(aa, dFrom, dTo) OR quantitySoldArticleDateFromTo(aa, dFrom, dTo) DEFAULT
        FILTER 'Артикул с продажей' 'F6' quantitySoldArticleDateFromTo(aa, dFrom, dTo)
        FILTER 'Артикул с поступлением' 'F5' quantityReceivedArticleDateFromTo(aa, dFrom, dTo)
;

DESIGN salesArticle FROM DEFAULT {

    main {
        NEW topContainer {
            childConstraints = TO THE BOTTOM;
            NEW wor {
                childConstraints = TO THE BOTTOM;
                ADD dates.box {
                    childConstraints = TO THE RIGHT;

                }
                ADD s.box {
                    childConstraints = TO THE RIGHT;
                    PROPERTY (nameSup){preferredCharWidth = 25;}
                }
            }
            NEW row {
                childConstraints = TO THE RIGHT;
                type = SPLITH;
                NEW row1 {
                    fillHorizontal = 1;
                    childConstraints = TO THE BOTTOM;

                    ADD b.box;
                    ADD c.box;
                    ADD sc.box;
                }

                ADD aa.box {
                    fillHorizontal = 2.5;
                }
            }
        }
        ADD functions.box;
    }
    PROPERTY(balanceBArticleDate) {
        caption = 'Остаток на начало';
    }
    PROPERTY(balanceAArticleDate) {
        caption = 'Остаток на конец';
    }

}

FORM salesArticleTheme 'Продажи по темам'

    OBJECTS dates = (dFrom = DATE, dTo = DATE) FIXED PANEL
    PROPERTIES valFrom = OBJVALUE(dFrom), valTo = OBJVALUE(dTo)

    OBJECTS s=supplier FIXED PANEL
    PROPERTIES     SELECTOR nameSup = name(s)
    PROPERTIES     READONLY balanceBSupplierDate(s,dFrom), quantityReceivedSupplierDateFromTo(s,dFrom,dTo), quantitySoldSupplierDateFromTo(s,dFrom,dTo), balanceASupplierDate(s,dTo),
                   percentBalanceReceivedSupplierDateFromTo(s,dFrom,dTo), sumSoldSupplierDateFromTo(s,dFrom,dTo)

    OBJECTS b=brandSupplier
    PROPERTIES     READONLY nameBr = name(b), balanceBBrandSupplierDate(b,dFrom), quantityReceivedBrandSupplierDateFromTo(b,dFrom,dTo), quantitySoldBrandSupplierDateFromTo(b,dFrom,dTo), balanceABrandSupplierDate(b,dTo),
                   percentBalanceReceivedBrandSupplierDateFromTo(b,dFrom,dTo), sumSoldBrandSupplierDateFromTo(b,dFrom,dTo)

    OBJECTS t=themeSupplier
    PROPERTIES     READONLY nameTh = name(t), balanceBThemeSupplierDate(t,dFrom), quantityReceivedThemeSupplierDateFromTo(t,dFrom,dTo), quantitySoldThemeSupplierDateFromTo(t,dFrom,dTo), balanceAThemeSupplierDate(t,dTo),
                   percentBalanceReceivedThemeSupplierDateFromTo(t,dFrom,dTo), sumSoldThemeSupplierDateFromTo(t,dFrom,dTo)

    OBJECTS aa=article
    PROPERTIES (aa)READONLY sidArticle, nameSupplierArticle, nameBrandSupplierArticle, nameCategorySupplierArticle, nameSubCategorySupplierArticle, nameThemeSupplierArticle

    PROPERTIES  READONLY balanceBArticleDate(aa,dFrom), quantityReceivedArticleDateFromTo(aa, dFrom, dTo), quantitySoldArticleDateFromTo(aa, dFrom, dTo),
                balanceAArticleDate(aa, dTo), percentBalanceReceivedArticleDateFromTo(aa, dFrom, dTo), sumSoldArticleDateFromTo(aa, dFrom, dTo)

    FILTERS  supplierBrandSupplier(b) == s,
             supplierThemeSupplier(t) == s

    FILTERGROUP filtersSold
        FILTER 'Артикул поставщика' 'F10' supplierArticle(aa) == s
        FILTER 'Артикул бренда' 'F9' brandSupplierArticle(aa) ==b


    FILTERGROUP filtersSold1
        FILTER 'Артикул темы' 'F8' themeSupplierArticle(aa) == t DEFAULT

    FILTERGROUP filtersSoldArticle
        FILTER 'Артикул с движением' 'F11' quantityReceivedArticleDateFromTo(aa, dFrom, dTo) OR quantitySoldArticleDateFromTo(aa, dFrom, dTo) DEFAULT
        FILTER 'Артикул с продажей' 'F6' quantitySoldArticleDateFromTo(aa, dFrom, dTo)
        FILTER 'Артикул с поступлением' 'F5' quantityReceivedArticleDateFromTo(aa, dFrom, dTo)
;

DESIGN salesArticleTheme FROM DEFAULT {

    main {
        NEW topContainer {
            childConstraints = TO THE BOTTOM;
            NEW wor {
                childConstraints = TO THE BOTTOM;
                ADD dates.box {
                    childConstraints = TO THE RIGHT;

                }
                ADD s.box {
                    childConstraints = TO THE RIGHT;
                    PROPERTY (nameSup){preferredCharWidth = 25;}
                }
            }
            NEW row {
                childConstraints = TO THE RIGHT;
                type = SPLITH;
                NEW row1 {
                    fillHorizontal = 1;
                    childConstraints = TO THE BOTTOM;

                    ADD b.box;
                    ADD t.box;
                }

                ADD aa.box {
                    fillHorizontal = 2.5;
                }
            }
        }
        ADD functions.box;
    }
    PROPERTY(balanceBArticleDate) {
        caption = 'Остаток на начало';
    }
    PROPERTY(balanceAArticleDate) {
        caption = 'Остаток на конец';
    }
}


NAVIGATOR {
    salesNavigator 'Продажи' {
        ADD salesArticle;
        ADD salesArticleTheme;
    }
}