MODULE RomanCashOperation;

REQUIRE System, CashOperation, RomanPOS;

NAMESPACE CashOperation;

CLASS accountCollection 'Изъятие (упр.)' : outcomeCashOrder, historyObject, numeratedObject;
TABLE accountCollection (accountCollection);

@defineNumeratedObjectDefault(accountCollection, 'Нумератор для изъятий', 'ИЗ');

@defineDocumentHeaderTime(accountCollection);

zReportAccountCollection 'Z-отчет (ИД)' (accountCollection) = DATA zReport (accountCollection);

cashRegisterAccountCollection (accountCollection) = cashRegisterZReport(zReportAccountCollection(accountCollection));
numberCashRegisterAccountCollection 'Касса инкассации' (accountCollection) =
    numberCashRegister(cashRegisterAccountCollection(accountCollection)) IN documentPrmGroup;

departmentStoreAccountCollection (accountCollection) = departmentStoreZReport(zReportAccountCollection(accountCollection));
nameDepartmentStoreAccountCollection 'Отдел' (accountCollection) = name(departmentStoreAccountCollection (accountCollection));

sumCashAccountCollection 'Сумма изъятия' = DATA NUMERIC[16,2] (accountCollection) IN documentSumGroup;

castBasisAccountCollection =
    FORMULA STRING[100] '\'Изъятие №\' || CAST($1 AS TEXT) || \' с кассы \' || CAST($2 AS TEXT) || \' от \' || CAST($3 AS TEXT)';
basisAccountCollection 'Основание' (accountCollection) =
    castBasisCollection(seriesNumberObject(accountCollection), dateAccountCollection(accountCollection)) IN documentPrmGroup;

dateCashDocument(accountCollection) += dateAccountCollection(accountCollection);
timeCashDocument(accountCollection) += timeAccountCollection(accountCollection);
numberCashDocument(accountCollection) += seriesNumberObject(accountCollection) AND accountCollection IS accountCollection;
departmentStoreCashDocument(accountCollection) += departmentStoreAccountCollection(accountCollection);
cashRegisterCashDocument(accountCollection) += cashRegisterAccountCollection(accountCollection);
sumCashOutcomeCashOrder(accountCollection) += sumCashAccountCollection(accountCollection);
basisCashDocument(accountCollection) += basisAccountCollection(accountCollection);
isPostedCashDocument(accountCollection) += TRUE AND accountCollection IS accountCollection;

//sumCashIncomeCashOrder(zReport) += sumCashZReport(zReport) (-) sumSkipAReceiptSaleDetailZReport(zReport);

createAccountCollectionZReport 'Изъять сумму' (zReport) = ACTION (zReport) {
    EXEC selectDialogSkipAReceiptDetailZReport (zReport);
    ADDOBJ accountCollection;
    FOR a == addedObject() DO {
        SET zReportAccountCollection (a) <- zReport;
        SET dateCashDocument (a) <- currentDate();
        SET timeCashDocument (a) <- currentTime();
        SET sumCashAccountCollection (a) <- selectSkipAReceiptDetailZReportSumSelected ();
    }
} TOOLBAR;

EXTEND FORM centralCashRegister PROPERTIES (i) createAccountCollectionZReport;



