MODULE RomanDocument;

REQUIRE Document;

META defineRBDocument (object, stock, stockCaption, skuProp, caption)

    @defineDocumentBasePosted(object);

    @defineDocumentStock(object, stock, stockCaption);

    @defineDocumentDetailQuantity(object);

    @defineDocumentDetailNumbered(object);

    @defineDocumentHeaderQuantity(object);

    description###object 'Название документа' (object) =
        [FORMULA STRING[200]  ' CAST($1 AS TEXT) || \' № \' || CAST($2 AS TEXT) || \' от \' || CAST($3 AS TEXT)'](
        caption, seriesNumberObject(object), date###object(object));

    description###object##Detail 'Название документа' (object) = description###object(object###object##Detail(object));

    @implementBalanceSkuLedger (object, skuProp, stock);

    @defineDocumentDetailProps (object);
END

META defineRBCorrespondingDocument (object, stock, stockCaption, skuProp, caption, corresponder, corresponderCaption)

    @defineRBDocument (object, stock, stockCaption, skuProp, caption);

    corresponder###object (object) = DATA corresponder (object);
    name###corresponder###object corresponderCaption (object) = name (corresponder###object(object));

END

// для использования метакода должно быть определено свойство sku###object##Detail
META defineDocumentDetailProps (object)

    barcode###object##Detail 'Штрих-код' (object##Detail) = barcode(sku###object##Detail(object##Detail));

    sidSize###object##Detail 'Размер' (object##Detail) = sidSizeSupplierItem(sku###object##Detail(object##Detail));
    sidColor###object##Detail 'Цвет (код)' (object##Detail) = sidColorSupplierItem(sku###object##Detail(object##Detail));
    nameColor###object##Detail 'Цвет' (object##Detail) = nameColorSupplierItem(sku###object##Detail(object##Detail));

    article###object##Detail 'Артикул (ИД)' (object##Detail) = articleSku(sku###object##Detail(object##Detail)) IN idGroup;
    sidArticle###object##Detail 'Артикул' (object##Detail) = sidArticle(article###object##Detail(object##Detail));
    brand###object##Detail 'Бренд (ИД)' (object##Detail) = brandSupplierArticle(article###object##Detail(object##Detail)) IN idGroup;
    nameBrand###object##Detail 'Бренд' (object##Detail) = name(brand###object##Detail(object##Detail));
    category###object##Detail 'Номенклатурная группа (ИД)' (object##Detail) = categoryArticle(article###object##Detail(object##Detail)) IN idGroup;
    nameCategory###object##Detail 'Номенклатурная группа' (object##Detail) = name(category###object##Detail(object##Detail));
END