MODULE Transfer;

REQUIRE System,
        Document,
        RomanDocument,
        Stock,
        RomanStock,
        DocumentTransfer,
        ListRegister,
        RetailPrice,
        Employee,
        StorePriceTransfer,
        Consignment,
        AccountDocument,
        ContractCompany,
        RomanLogicsModule;

PRIORITY Stock, RomanLogicsModule;

// ---------------------------------------- Перемещение ------------------------------------ //

CLASS transferOut 'Перемещение товаров по накладным' : historyObject, numberedObject, innerDocument, consignment, outAccountDocumentLedger;
CLASS transferOutPosted 'Проведенное перемещение товаров по накладным' : transferOut, postedObject;
CLASS transferOutDetail 'Строка перемещения товаров по накладным';
CLASS transferOutBatchDetail 'Строка перемещения товаров по накладным (по партиям)' : consignmentDetail;

@defineDocumentTransferOut(transfer, 'Перемещение товаров по накладным', sku, stock);
@defineDocumentFormTransferOut(transfer, 'Перемещение товаров по накладным');

@defineDocumentCurrency(transferOut);
@deriveDocumentCurrency(transferOut, stock);

CONSTRAINT legalEntityTransferOut(transferOut) != destinationLegalEntityTransferOut(transferOut) CHECKED BY destinationStockTransferOut
    MESSAGE 'Перемещение товаров должно идти между складами одной компании';

@defineDocumentDetailSkuArticle(transferOut);
@extendFormDocumentDetailSkuArticle(transferOut, d, transferOut);
@extendFormDocumentDetailSkuArticleReadonly(transferOuts, d, transferOut);

// Перемещение по договорам комиссии
commissionContractSkuTransferOut = DATA contractSku (transferOut);
numberCommissionContractSkuTransferOut 'Номер договора комиссии' (transferOut) = numberContract(commissionContractSkuTransferOut(transferOut)) IN documentPrmGroup;

isCommissionTransferOut 'Продажа на комиссию' (transferOut) = TRUE IF commissionContractSkuTransferOut(transferOut);

CONSTRAINT typeContractSkuDate(commissionContractSkuTransferOut(transferOut), dateTransferOut(transferOut)) != contractSkuType.commission
    CHECKED BY commissionContractSkuTransferOut MESSAGE 'Для перемещения выбран договор, который не является договором комиссии';

CONSTRAINT partyBContract(commissionContractSkuTransferOut(transferOut)) != legalEntityTransferOut(transferOut)
    CHECKED BY commissionContractSkuTransferOut MESSAGE 'Для перемещения выбран договор комиссии, у которого покупатель не совпадает с компанией склада';

EXTEND FORM transferOut
    PROPERTIES(t) numberCommissionContractSkuTransferOut
;

EXTEND FORM transferOuts
    PROPERTIES(t) READONLY numberCommissionContractSkuTransferOut
;

commissionContractSkuTransferOutDetail (detail) = commissionContractSkuTransferOut(transferOutTransferOutDetail(detail)) PERSISTENT;

@defineDocumentTransferOutBatch(transfer, sku);
@defineDocumentFormTransferOutBatch(transfer);

@extendFormDocumentDetailSkuArticleReadonly(transferOuts, o, transferOutBatch);

@defineDocumentRetailPrice(transferOut, d);

useRetailPriceTransferOutDetail(detail) = [stockTransferOutDetail(detail) IS departmentStore
    AND NOT costLedgerDepartmentStore(stockTransferOutDetail(detail))](detail)
    OR commissionContractSkuTransferOutDetail(detail) IS contractSku;
@defineDocumentTransferAccount(transferOut, useRetailPriceTransferOutDetail);

importerPriceTransferOutBatchDetail 'Цена импортера' (detail) = importerPriceBatchA(batchTransferOutBatchDetail(detail));
supplierPriceTransferOutBatchDetail 'Цена поставщика' (detail) = supplierPriceBatchA(batchTransferOutBatchDetail(detail));
EXTEND FORM transferOuts
    PROPERTIES(o) READONLY importerPriceTransferOutBatchDetail, supplierPriceTransferOutBatchDetail
;

@defineDocumentSkipSkuLedgerCustom(transferOut, transferOutDetail);
@extendFormDocumentSkipSkuLedgerCustom(transferOut, t, transferOut);
@extendFormDocumentSkipSkuLedgerCustomReadonly(transferOuts, t, transferOut);

// Проводим по регистру
@implementSkuLedgerOutFIFO(transferOut, sku, stock);
quantityOutFIFOSkuLedger (ledger) += quantityTransferOutDetail (ledger);
limitOutFIFOSkuLedgerBatch(ledger, batch) += IF commissionContractSkuTransferOutDetail(ledger)
                                                THEN currentBalanceABatchStock(batch, stockTransferOutDetail(ledger)) AND commissionContractSkuBatchA(batch) == commissionContractSkuTransferOutDetail(ledger)
                                                ELSE currentBalanceABatchStock(batch, stockTransferOutDetail(ledger)) AND NOT commissionContractSkuBatchA(batch)
                                             AND batch IS batchA;
sumOutSkuLedger(ledger) += accountSumTransferOutDetail(ledger);
skipSkuLedger (ledger) += skipSkuLedgerTransferOutDetail(ledger);

// Запрет на не полностью расписанные партии
@defineConstraintSkuLedgerCosted(transferOut, 'Не хватает остатков по партиям для перемещения товаров');

// Товарные накладные
@defineDocumentDetailPackWeightSku(transferOutBatch); // вес и к-во мест для партий

@defineConsignment(transferOut);
@implementConsignmentHeader(transferOut, stock);

senderConsignment (consignment) += legalEntityStock(stockTransferOut(consignment));
recipientConsignment (consignment) += legalEntityStock(destinationStockTransferOut(consignment));
consignmentConsignmentDetail (consignmentDetail) += transferOutTransferOutBatchDetail (consignmentDetail);
skuConsignmentDetail (consignmentDetail) += skuTransferOutBatchDetail (consignmentDetail);
quantityConsignmentDetail (consignmentDetail) += quantityTransferOutBatchDetail (consignmentDetail);

isStockToStockTransferOut 'Перемещение м/у складами' (transferOut) =  GROUP SUM 1
    IF stockTransferOut(transferOut) == warehouse AS warehouse AND destinationStockTransferOut(transferOut) == warehouse AS warehouse
    BY transferOut;

isStockToStockTransferOutBatchDetail 'Перемещение м/у складами' (transferOutBatchDetail) = isStockToStockTransferOut(transferOutTransferOutBatchDetail(transferOutBatchDetail));
isCommissionTransferOutBatchDetail 'Продажа на комиссию' (transferOutBatchDetail) = isCommissionTransferOut(transferOutTransferOutBatchDetail(transferOutBatchDetail));

supplierSumTransferOutBatchDetail (transferOutBatchDetail) =  supplierPriceBatchA(batchTransferOutBatchDetail(transferOutBatchDetail)) * quantityTransferOutBatchDetail (transferOutBatchDetail);
sumVatTransferOutBatchDetail (transferOutBatchDetail) = [round0(X*Y/100)](
    valueSupplierVATBatchA(batchTransferOutBatchDetail(transferOutBatchDetail)), supplierSumTransferOutBatchDetail(transferOutBatchDetail));
sumInvoiceTransferOutBatchDetail (transferOutBatchDetail) = supplierSumTransferOutBatchDetail(transferOutBatchDetail) (+) sumVatTransferOutBatchDetail(transferOutBatchDetail);

priceConsignmentDetail (consignmentDetail) += IF isStockToStockTransferOutBatchDetail(consignmentDetail) AND NOT isCommissionTransferOutBatchDetail(consignmentDetail)
    THEN supplierPriceBatchA(batchTransferOutBatchDetail(consignmentDetail))
    ELSE retailPriceTransferOutDetail(transferOutDetailTransferOutBatchDetail(consignmentDetail));

sumConsignmentDetail (consignmentDetail) += IF isStockToStockTransferOutBatchDetail(consignmentDetail) AND NOT isCommissionTransferOutBatchDetail(consignmentDetail)
    THEN supplierSumTransferOutBatchDetail(consignmentDetail)
    ELSE retailPriceTransferOutDetail(transferOutDetailTransferOutBatchDetail(consignmentDetail))* quantityTransferOutBatchDetail (consignmentDetail);

vatConsignmentDetail (consignmentDetail) += valueSupplierVATBatchA(batchTransferOutBatchDetail(consignmentDetail)) IF isStockToStockTransferOutBatchDetail(consignmentDetail) AND NOT isCommissionTransferOutBatchDetail(consignmentDetail);

sumVATConsignmentDetail (consignmentDetail) += sumVatTransferOutBatchDetail(consignmentDetail) IF isStockToStockTransferOutBatchDetail(consignmentDetail) AND NOT isCommissionTransferOutBatchDetail(consignmentDetail);

sumInvoiceConsignmentDetail (consignmentDetail) += IF isStockToStockTransferOutBatchDetail(consignmentDetail) AND NOT isCommissionTransferOutBatchDetail(consignmentDetail)
    THEN sumInvoiceTransferOutBatchDetail(consignmentDetail)
    ELSE retailPriceTransferOutDetail(transferOutDetailTransferOutBatchDetail(consignmentDetail)) * quantityTransferOutBatchDetail (consignmentDetail);

grossWeightConsignmentDetail (consignmentDetail) += grossWeightTransferOutBatchDetail (consignmentDetail);
packQuantityConsignmentDetail (consignmentDetail) += packQuantityTransferOutBatchDetail (consignmentDetail);
shortNameUOMConsignmentDetail (consignmentDetail) += shortNameUOMTransferOutBatchDetail (consignmentDetail);

@defineDocumentFormTransferOutConsignment(transfer, t);
// todo: заполнить необходимыми данными

EXTEND FORM transferOut
    PROPERTIES(t) nameCurrencyTransferOut
;
EXTEND FORM transferOuts
    PROPERTIES(t) READONLY nameCurrencyTransferOut
;
// ---------------------------------------- Поступление ------------------------------------ //

CLASS transferIn 'Поступление товаров по накладным' : historyObject, incAccountDocumentLedger;
CLASS transferInDetail 'Строка поступления товаров по накладным';

@defineDocumentTransferIn(transfer, 'Поступление товаров по накладным', sku, stock);
@defineDocumentFormTransferIn(transfer, 'Поступление товаров по накладным');

costTransferInBatch(transferIn, batch) = GROUP SUM costSkuLedgerBatch(ledger, batch) BY transferInTransferInDetail(ledger), batch PERSISTENT;

retailPriceTransferInDetail 'Цена розничная' (detail) = retailPriceTransferOutDetail(transferOutDetailTransferInDetail(detail));
retailSumTransferInDetail 'Сумма розничная' (detail) = quantityTransferInDetail(detail) * retailPriceTransferInDetail(detail);

skipSkuLedgerTransferIn 'Не проводить по учету' (transferIn) = skipSkuLedgerTransferOut(transferOutTransferIn(transferIn));
skipSkuLedgerTransferInDetail (detail) = skipSkuLedgerTransferOutDetail(transferOutDetailTransferInDetail(detail));

commissionContractSkuTransferInDetail (detail) = commissionContractSkuTransferOutDetail(transferOutDetailTransferInDetail(detail));

@defineDocumentDetailSkuArticle(transferIn);
@extendFormDocumentDetailSkuArticleReadonly(transferIns, d, transferIn);
@extendFormDocumentSkipSkuLedgerCustomReadonly(transferIns, t, transferIn);

useRetailPriceTransferInDetail(detail) = [stockTransferInDetail(detail) IS departmentStore
    AND NOT costLedgerDepartmentStore(stockTransferInDetail(detail))](detail)
    OR commissionContractSkuTransferInDetail(detail) IS contractSku;
@defineDocumentTransferAccount(transferIn, useRetailPriceTransferInDetail);

@implementSkuLedgerInLIFO(transferIn, sku, stock);
quantityInLIFOSkuLedger (ledger) += quantityTransferInDetail(ledger);
limitInLIFOSkuLedgerBatch (ledger, batch) += costSkuLedgerBatch(transferOutDetailTransferInDetail(ledger), batch);
sumInSkuLedger(ledger) += accountSumTransferInDetail(ledger);
skipSkuLedger (ledger) += skipSkuLedgerTransferInDetail(ledger);

nameCurrencyTransferIn 'Валюта' (transferIn) = nameCurrencyTransferOut(transferOutTransferIn(transferIn)) MINCHARWIDTH 10 PREFCHARWIDTH 10 MAXCHARWIDTH 15;

// ---------------------------------------- Приемка ------------------------------------ //

CLASS transferRec 'Приемка товаров по накладной (перемещение)' : historyObject;
CLASS transferRecPosted 'Проведенная приемка товаров по накладной (перемещение)' : transferRec, postedObject;

CLASS transferRecDetail 'Строка приемки товаров по накладной (перемещение)';

@defineDocumentTransferRec(transfer, 'Приемка товаров по накладным (перемещение)', sku, stock);
@defineDocumentFormTransferRec(transfer, 'Приемка товаров по накладным (перемещение)');

@defineDocumentDetailSkuArticle(transferRec);
@extendFormDocumentDetailSkuArticle(transferRec, d, transferRec);

@extendFormDocumentDetailSkuArticleReadonly(transferIns, r, transferRec);

// ---------------------------------------- Акт расхождений ------------------------------------ //
CLASS transferDiff 'Акт расхождений приемки товаров по накладной (перемещение)' : historyObject;

CLASS ABSTRACT transferDiffDetail 'Строка расхождений акта приемки товаров по накладной (перемещение)';
CLASS transferDiffEDetail 'Строка расхождений акта приемки товаров по накладной (перемещение, излишек)' : transferDiffDetail;
CLASS transferDiffSDetail 'Строка расхождений акта приемки товаров по накладной (перемещение, недостача)' : transferDiffDetail;

@defineDocumentTransferDiff(transfer, 'Акт расхождений приемки товаров по накладной (перемещение)', sku, stock);
@defineDocumentFormTransferDiff(transfer);

@defineDocumentDetailSkuArticle(transferDiff);
@extendFormDocumentDetailSkuArticleReadonlyQuantity(transferIns, f, transferDiff, signedQuantityTransferDiffDetail);

costTransferDiffEDetail(detail) = 0.0 IF detail IS transferDiffEDetail;
EXTEND CLASS transferDiffEDetail : batchB;
@implementBatchCustom(transferDiffE, sku, stock, cost);
quantityBatch (batch) += quantityTransferDiffEDetail(batch);
skipASkuLedger (ledger) += ledger IS transferDiffEDetail;

@implementSkuLedgerOutFIFO(transferDiffS, sku, stock);
quantityOutFIFOSkuLedger (ledger) += quantityTransferDiffSDetail(ledger);
limitOutFIFOSkuLedgerBatch (ledger, batch) += costTransferInBatch(transferInTransferDiffSDetail(ledger), batch);
orderOutFIFOSkuLedgerBatch (ledger, batch) += orderBBatch(batch) IF ledger IS transferDiffSDetail;

accountPriceTransferRecBatchA (transferRec, batchA) = GROUP MAX accountPriceTransferInDetailBatchA(detail, batchA) BY transferRecTransferInDetail(detail), batchA;
accountSumTransferDiffSDetail (detail) = GROUP SUM costDataSkuLedgerBatch(detail, batch) * accountPriceTransferRecBatchA(transferRecTransferDiffSDetail(detail), batch) BY detail PERSISTENT;
sumOutSkuLedger(ledger) += accountSumTransferDiffSDetail(ledger);

skipASkuLedger (ledger) += ledger IS transferDiffSDetail;

// ---------------------------------------- Акт расценки ------------------------------------ //
CLASS transferPriceActTransfer 'Акт расценки (внутр.)' : inputTransferPriceAct;
CLASS transferPriceActTransferDetail 'Строка акта расценки': inputTransferPriceActDetail;

prevImporterPriceBatch (batch) = PREV(importerPriceBatchA(batch)) AND batch IS batch;
prevSupplierPriceBatch (batch) = PREV(supplierPriceBatchA(batch)) AND batch IS batch;
prevRangeVATBatch (batch) = PREV(rangeVATBatchA(batch)) AND batch IS batch;

@defineDocumentTransferPriceAct (transfer, 'Акт расценки (перемещение)', 'Строка акта расценки (перемещение)', sku, stock, prevImporterPriceBatch, prevSupplierPriceBatch, prevRangeVATBatch);

notPassToBookkeepingListRegister (inputListRegister) += destinationStockTransferOut(transferOutTransferPriceActTransfer(inputListRegister)) IS departmentStore
    AND stockTransferOut(transferOutTransferPriceActTransfer(inputListRegister)) IS departmentStore
    OR  isCommissionTransferOut(transferOutTransferPriceActTransfer(inputListRegister));

printInputListRegisterTransferIn 'Реестр цен' (transferIn) = printInputListRegister(transferPriceActTransferTransferOut(transferOutTransferIn(transferIn))) TOOLBAR;


EXTEND FORM transferIns
    PROPERTIES(t) READONLY nameCurrencyTransferIn
    PROPERTIES (t) printInputListRegisterTransferIn
;

//---------------------------------------- Товарный отчет ------------------------- //

// расход
dateTimeAccountDocumentLedger (ledger) += dateTimeTransferOut(ledger);
isPostedAccountDocumentLedger (ledger) += isPostedTransferOut(ledger);
stockAccountDocumentLedger (ledger) += stockTransferOut(ledger);
descriptionAccountDocumentLedger (ledger) += descriptionTransferOut(ledger);

sumOutAccountDocumentLedger (ledger) += accountSumTransferOut(ledger);
sumItemOutAccountDocumentLedger (ledger) += accountSumTransferOut(ledger);
sumContainerOutAccountDocumentLedger (ledger) += 0.0 IF ledger IS transferOut;

// приход
dateTimeAccountDocumentLedger (ledger) += dateTimeTransferIn(ledger);
isPostedAccountDocumentLedger (ledger) += isPostedTransferIn(ledger);
stockAccountDocumentLedger (ledger) += stockTransferIn(ledger);
descriptionAccountDocumentLedger (ledger) += descriptionTransferIn(ledger);

sumIncAccountDocumentLedger (ledger) += accountSumTransferIn(ledger);
sumItemIncAccountDocumentLedger (ledger) += accountSumTransferIn(ledger);
sumContainerIncAccountDocumentLedger (ledger) += 0.0 IF ledger IS transferIn;
