//From WareHouse to Store (the posted)
MODULE WHtoSPosted;

REQUIRE System,

        Stock,
        Numerator,
        Document,
        RomanDocument,
        Declaration,
        WholesalePrice,
        MasterData,
        RomanLogicsModule;

PRIORITY RomanLogicsModule, Stock;

CLASS ABSTRACT WHtoSPosted 'Расход на магазин закрытый': numberedObject;
CLASS ABSTRACT WHtoSPostedDetail 'Строка расхода на магазин';


dateWHtoSPosted 'Дата' (WHtoSPosted) = ABSTRACT DATE (WHtoSPosted);
timeWHtoSPosted 'Время' (WHtoSPosted) = ABSTRACT TIME (WHtoSPosted);
warehouseWHtoSPosted 'Оптовый склад (ИД)' (WHtoSPosted) = ABSTRACT warehouse (WHtoSPosted);
nameWarehouseWHtoSPosted 'Оптовый склад' (WHtoSPosted) = name(warehouseWHtoSPosted(WHtoSPosted));
storeWHtoSPosted 'Магазин (ИД)' (WHtoSPosted) = ABSTRACT store (WHtoSPosted);
nameStoreWHtoSPosted 'Магазин-получатель' (WHtoSPosted) = name(storeWHtoSPosted(WHtoSPosted));

quantityWHtoSPostedDetailWHtoSPosted 'Кол-во (всего)' (WHtoSPosted) = ABSTRACT NUMERIC[16,2] (WHtoSPosted);
invoiceVATSumWHtoSPostedDetailWHtoSPosted 'Сумма НДС поставщика' (WHtoSPosted) = ABSTRACT NUMERIC[16,2] (WHtoSPosted);
invoiceSumWHtoSPostedDetailWHtoSPosted 'Сумма поставщика с НДС' (WHtoSPosted) = ABSTRACT NUMERIC[16,2] (WHtoSPosted);

quantityWHtoSPostedSku 'Кол-во плановое' (WHtoSPosted, sku) = ABSTRACT NUMERIC[16,2] (WHtoSPosted, sku);

//--------------------------Detail----------------------------------------------

WHtoSPostedWHtoSPostedDetail (WHtoSPostedDetail) = ABSTRACT WHtoSPosted (WHtoSPostedDetail);

skuWHtoSPostedDetail (WHtoSPostedDetail) = ABSTRACT sku (WHtoSPostedDetail);
UOMWHtoSPostedDetail (WHtoSPostedDetail) = ABSTRACT UOM (WHtoSPostedDetail);
quantityWHtoSPostedDetail 'Количество' (WHtoSPostedDetail) = ABSTRACT NUMERIC[14,3] (WHtoSPostedDetail);
importerPriceWHtoSPostedDetail 'Цена изготовителя/импортера' (WHtoSPostedDetail) = ABSTRACT NUMERIC[14,2] (WHtoSPostedDetail);
supplierPriceWHtoSPostedDetail 'Цена поставщика без НДС' (WHtoSPostedDetail) = ABSTRACT NUMERIC[14,2] (WHtoSPostedDetail);

//importerSumWHtoSPostedDetail 'Стоимость без НДС' (WHtoSPostedDetail) = ABSTRACT NUMERIC[16,2] (WHtoSPostedDetail);
supplierVATWHtoSPostedDetail(WHtoSPostedDetail) = ABSTRACT range (WHtoSPostedDetail);
CONSTRAINT taxRange(supplierVATWHtoSPostedDetail(WHtoSPostedDetail)) != tax.taxVAT CHECKED BY supplierVATWHtoSPostedDetail MESSAGE 'ошибка: Шкала должна соответствовать шкале НДС';

//sumVATWHtoSPostedDetail 'Сумма НДС' (WHtoSPostedDetail) = ABSTRACT NUMERIC[16,2] (WHtoSPostedDetail);
//sumInvoiceWHtoSPostedDetail 'Сумма с НДС' (WHtoSPostedDetail) = ABSTRACT NUMERIC[16,2] (WHtoSPostedDetail);


//    barcodeWHtoSPostedDetail 'Штрих-код' (object##Detail) = barcode(skuWHtoSPostedDetail(WHtoSPostedDetail));
//
//    sidSizeWHtoSPostedDetail 'Размер' (WHtoSPostedDetail) = sidSizeSupplierItem(skuWHtoSPostedDetail(WHtoSPostedDetail));
//    sidColorWHtoSPostedDetail 'Цвет (код)' (WHtoSPostedDetail) = sidColorSupplierItem(skuWHtoSPostedDetail(WHtoSPostedDetail));
//    nameColorWHtoSPostedDetail 'Цвет' (WHtoSPostedDetail) = nameColorSupplierItem(skuWHtoSPostedDetail(WHtoSPostedDetail));
//
//    articleWHtoSPostedDetail 'Артикул (ИД)' (WHtoSPostedDetail) = articleSku(skuWHtoSPostedDetail(WHtoSPostedDetail)) IN idGroup;
//    sidArticleWHtoSPostedDetail 'Артикул' (WHtoSPostedDetail) = sidArticle(articleWHtoSPostedDetail(WHtoSPostedDetail));
//
//    brandWHtoSPostedDetail 'Бренд (ИД)' (WHtoSPostedDetail) = brandSupplierArticle(articleWHtoSPostedDetail(WHtoSPostedDetail)) IN idGroup;
//    nameBrandWHtoSPostedDetail 'Бренд' (WHtoSPostedDetail) = name(brandWHtoSPostedDetail(WHtoSPostedDetail));
//
//    categoryWHtoSPostedDetail 'Номенклатурная группа (ИД)' (WHtoSPostedDetail) = categoryArticle(articleWHtoSPostedDetail(WHtoSPostedDetail)) IN idGroup;
//    nameCategoryWHtoSPostedDetail 'Номенклатурная группа' (WHtoSPostedDetail) = name(categoryWHtoSPostedDetail(WHtoSPostedDetail));


FORM WHtoSPostedDialog 'Расходы на магазин'
    OBJECTS w = WHtoSPosted
    PROPERTIES (w) READONLY objectClassName, numberObject, seriesObject, dateWHtoSPosted, timeWHtoSPosted, nameWarehouseWHtoSPosted, nameStoreWHtoSPosted,
                   quantityWHtoSPostedDetailWHtoSPosted, invoiceVATSumWHtoSPostedDetailWHtoSPosted, invoiceSumWHtoSPostedDetailWHtoSPosted

    DIALOG WHtoSPosted OBJECT w
;

