MODULE LabelRepricing;

REQUIRE Repricing, Label;

NAMESPACE Repricing;

// ------------------------------------- Печать ценников ------------------------------ //

@Label.implementPriceTransactionDocument(repricing);
Label.skipPriceTransactionDocument(document) += skipChangeLedgerRepricing(document);

@defineDocumentLabelTransaction(repricing, sku, departmentStore);
@extendFormDocumentLabelTransaction(repricings, p, repricing);