mkdir "%USERPROFILE%\.IntelliJIdea10\config\filetypes"
mkdir "%USERPROFILE%\.IntelliJIdea11\config\filetypes"
mkdir "%USERPROFILE%\.IntelliJIdea12\config\filetypes"
copy /Y FusionScript.xml "%USERPROFILE%\.IntelliJIdea10\config\filetypes\FusionScript.xml"
copy /Y FusionScript.xml "%USERPROFILE%\.IntelliJIdea11\config\filetypes\FusionScript.xml"
copy /Y FusionScript.xml "%USERPROFILE%\.IntelliJIdea12\config\filetypes\FusionScript.xml"
