MODULE SaleBlanketOrderTaxReverse;

REQUIRE TaxReverse, SaleBlanketOrder;

NAMESPACE Sale;

overValueVATBlanketOrderDetail(detail) += NUMERIC[10,5](valueRateRangeDate(VATBlanketOrderDetail(detail), dateBlanketOrderDetail(detail)) * 100 /
                                                        (100-valueRateRangeDate(VATBlanketOrderDetail(detail), dateBlanketOrderDetail(detail))))
                                          IF reverseRange(VATBlanketOrderDetail(detail));