MODULE SaleInvoiceRRP;

REQUIRE SaleInvoice;

NAMESPACE Sale;

//------------------------- Рекомендуемая розничная цена-------------------------//

@defineDocumentInterfaceHeaderCreate (invoice, toShowRRPPrice, 'RRP');
@defineDocumentInterfaceDetailPriceListType (invoice, priceListType, RRP, ' (RRP)');

RRPPriceListTypeUserInvoiceDetail(userInvoiceDetail) <- RRPPriceListTypeAgreement(agreementUserInvoice(userInvoiceUserInvoiceDetail(userInvoiceDetail)))
    WHEN CHANGED (agreementUserInvoice(userInvoiceUserInvoiceDetail(userInvoiceDetail)));

currencyRRPUserInvoiceDetail (userInvoiceDetail) = currencyPriceListType(RRPPriceListTypeUserInvoiceDetail(userInvoiceDetail));
nameCurrencyRRPUserInvoiceDetail 'Валюта (RRP)' (userInvoiceDetail) = name(currencyRRPUserInvoiceDetail(userInvoiceDetail));

currencyRRPInvoiceDetail (invoiceDetail) = currencyPriceListType(RRPPriceListTypeInvoiceDetail(invoiceDetail));
nameCurrencyRRPInvoiceDetail 'Валюта (RRP)' (invoiceDetail) = name(currencyRRPInvoiceDetail(invoiceDetail));

@defineDocumentInterfaceDetailPriceCustomPrefix (invoiceDetail, RRP, ' (RRP)');
RRPPriceUserInvoiceDetail (detail)  <-  prevPricePriceListTypeSkuStockDateTime(RRPPriceListTypeUserInvoiceDetail(detail),
                                                                               skuUserInvoiceDetail(detail),
                                                                               supplierStockUserInvoiceDetail(detail),
                                                                               dateTimeUserInvoiceDetail(detail))
                                                    WHEN CHANGED(RRPPriceListTypeUserInvoiceDetail(detail)) OR
                                                         CHANGED(skuUserInvoiceDetail(detail)) OR
                                                         CHANGED(supplierStockUserInvoiceDetail(detail)) OR
                                                         CHANGED(dateTimeUserInvoiceDetail(detail));

RRPSumUserInvoiceDetail 'Сумма (RRP)' (detail) = roundPriceCurrency(RRPPriceUserInvoiceDetail (detail)*quantityUserInvoiceDetail(detail), currencyUserInvoiceDetail(detail));
RRPSumInvoiceDetail 'Сумма (RRP)' (detail) = roundPriceCurrency(RRPPriceInvoiceDetail(detail)*quantityInvoiceDetail(detail), currencyInvoiceDetail(detail));

EXTEND FORM userInvoice
    PROPERTIES(i) toShowRRPPriceUserInvoice
    PROPERTIES(d) SHOWIF toShowRRPPriceUserInvoice(i) BEFORE delete(d) nameRRPPriceListTypeUserInvoiceDetail, nameCurrencyRRPUserInvoiceDetail READONLY, RRPPriceUserInvoiceDetail
;
EXTEND DESIGN userInvoice {
    headerExtraParams {
        NEW headerRRP {
            title = 'RRP';
            ADD PROPERTY(toShowRRPPriceUserInvoice);
        }
    }
}

EXTEND FORM invoices
    PROPERTIES(i) READONLY toShowRRPPriceInvoice
    PROPERTIES(d) READONLY SHOWIF toShowRRPPriceInvoice(i) nameRRPPriceListTypeInvoiceDetail, nameCurrencyRRPInvoiceDetail, RRPPriceInvoiceDetail
;

//-- Операция
toShowRRPPriceUserInvoice (invoice) <- toShowRRPPriceOperation(operationUserInvoice(invoice))
    WHEN CHANGED(operationUserInvoice(invoice));
