
!define IDEA_MAJORVERSION 2016
!define JDK_MAJORVERSION 1.8

!define PG_VERSION 9.5
!define JDK_VERSION ${JDK_MAJORVERSION}.0_101
!define IDEA_VERSION ${IDEA_MAJORVERSION}.2.5

!define PG_MINORVERSION .4
!define JDK_DISTRVERSION 8u101
