!define IDEA_MAJORVERSION 2017.2
!define IDEA_VERSION ${IDEA_MAJORVERSION}.4

!define JDK_MAJORVERSION 1.8
!define JDK_VERSION ${JDK_MAJORVERSION}.0_144
!define JDK_DISTRVERSION 8u144

!define PG_VERSION 9.6
!define PG_MINORVERSION .5

!define TOMCAT_MAJOR_VERSION 8
!define TOMCAT_VERSION ${TOMCAT_MAJOR_VERSION}.5
!define TOMCAT_FULL_VERSION ${TOMCAT_VERSION}.20
