
!define IDEA_MAJORVERSION 14
!define JDK_MAJORVERSION 1.7

!define PG_VERSION 9.4
!define JDK_VERSION ${JDK_MAJORVERSION}.0_75
!define IDEA_VERSION ${IDEA_MAJORVERSION}.0.3

!define PG_MINORVERSION .0
!define JDK_DISTRVERSION 7u75
