MODULE Printer;

REQUIRE System;

//text, charset, printerName
writeToPrinter '{printer.write.to.printer}'  INTERNAL  'lsfusion.server.physics.dev.integration.external.to.equ.printer.WriteToPrinterAction' (TEXT, STRING[255], ISTRING[255]);
writeToServerPrinter '{printer.write.to.server.printer}'  INTERNAL  'lsfusion.server.physics.dev.integration.external.to.equ.printer.WriteToServerPrinterAction' (TEXT, STRING[255], ISTRING[255]);
printed '{printer.printed}' = DATA LOCAL BOOLEAN ();

getAvailablePrinters '{printer.get.available.printers}'  INTERNAL  'lsfusion.server.physics.dev.integration.external.to.equ.printer.GetAvailablePrintersAction' ();

//text, charset, ip, port
writeToSocketAction  INTERNAL  'lsfusion.server.physics.dev.integration.external.to.equ.printer.WriteToServerSocketAction' (TEXT, STRING[10], STRING[30], INTEGER);