MODULE SQLUtils;

REQUIRE System, Authentication, Service, Utils, Time, ProcessMonitor;

runSQL '{sql.utils.run.sql}'  INTERNAL  'lsfusion.utils.admin.interpreter.RunSQLScriptActionProperty' (TEXT);

runJDBC '{sql.utils.run.jdbc}'  INTERNAL  'lsfusion.utils.admin.interpreter.RunJDBCStatementActionProperty' (VARSTRING[100], TEXT);

vacuumTableAction '{sql.utils.vacuum.table.action}'(Table table)  { 
    runSQL('VACUUM FULL ' + sid(table));
}

vacuumTablesAction '{sql.utils.vacuum.tables.action}' ()  { 
    FOR table IS Table AND NOT skipVacuum(table) ORDER rows(table) DO {
        vacuumTableAction(table);
    }
    
    //vacuum части системных таблиц
    runSQL('VACUUM FULL pg_catalog.pg_statistic');
    runSQL('VACUUM FULL pg_catalog.pg_attribute');
    runSQL('VACUUM FULL pg_catalog.pg_class');
    runSQL('VACUUM FULL pg_catalog.pg_depend');
    runSQL('VACUUM FULL pg_catalog.pg_type');
    runSQL('VACUUM FULL pg_catalog.pg_constraint');
    runSQL('VACUUM FULL pg_catalog.pg_index');
    runSQL('VACUUM FULL pg_catalog.pg_proc');
    
    MESSAGE '{sql.utils.message.vacuum.tables.action}';
}

alterTableColumnsToLong '{sql.utils.alter.table.columns.to.long}'  INTERNAL  'lsfusion.utils.admin.migration.AlterTableColumnsToLongActionProperty' (Table);

EXTEND FORM physicalModel PROPERTIES(t) BEFORE skipVacuum(t) GRID vacuumTableAction, alterTableColumnsToLong;
EXTEND FORM maintenance PROPERTIES() vacuumTablesAction;
DESIGN maintenance {
    database {
        MOVE PROPERTY(vacuumTablesAction());
    }
}

changeAllDates '{sql.utils.change.all.dates}'  INTERNAL  'lsfusion.utils.admin.migration.ChangeAllDatesActionProperty' () CONFIRM;
secondsChangeAllDates '{sql.utils.seconds.change.all.dates}' = DATA INTEGER ();

EXTEND FORM maintenance PROPERTIES() changeAllDates, secondsChangeAllDates;
DESIGN maintenance {
    rightColumn {
        NEW changeDates {
            caption = '{sql.utils.caption.change.dates}';
            MOVE PROPERTY(changeAllDates());
            MOVE PROPERTY(secondsChangeAllDates());
        }
    }
}
