MODULE SaleInvoiceTaxReverse;

REQUIRE TaxReverse, SaleInvoice;

NAMESPACE Sale;

overValueVATUserInvoiceDetail(detail) += valueRateRangeDate(VATUserInvoiceDetail(detail), dateUserInvoiceDetail(detail)) * 100 /
                                    (100-valueRateRangeDate(VATUserInvoiceDetail(detail), dateUserInvoiceDetail(detail)))
                                    IF reverseRange(VATUserInvoiceDetail(detail));