MODULE RepricingManufacturingPrice;

REQUIRE Repricing;

@defineDocumentInterfaceDetailPriceCustomPrefix(repricingDetail, manufacturing, ' изготовителя после');

@defineDocumentInterfaceDetailPriceCustomPrefix(repricingDetail, curManufacturing, ' изготовителя до');
@deriveDocumentDetailPriceSystemLedgerPriceListType(userRepricing, manufacturingPriceStockPriceListType, curManufacturing, sku, departmentStore);

overManagementRepricing(detail, sku, department, time) += ACTION (detail, sku, department, time) {
    SET manufacturingPriceUserRepricingDetail(detail) <- prevPricePriceListTypeSkuStockDateTime(SystemLedgerPriceListType.manufacturingPriceStockPriceListType, sku, department, time)
        WHERE prevPricePriceListTypeSkuStockDateTime(SystemLedgerPriceListType.manufacturingPriceStockPriceListType, sku, department, time);
}

@changeDocumentDetailPricePrefix(userRepricingDetail, curManufacturing, cur, cur, curManufacturing, cur, curRetail);
@changeDocumentDetailPricePrefix(userRepricingDetail, manufacturing, newRetail, , manufacturing, , retail);

overRepricingPriceUserRepricingDetail(detail) += manufacturingPriceUserRepricingDetail(detail);
overCurRepricingPriceUserRepricingDetail(detail) += curManufacturingPriceUserRepricingDetail(detail);

EXTEND FORM userRepricing
    PROPERTIES(d) manufacturingPriceUserRepricingDetail ON CHANGE changeManufacturingPriceUserRepricingDetail(d) BEFORE priceUserRepricingDetail,
                  curManufacturingPriceUserRepricingDetail ON CHANGE changeCurManufacturingPriceUserRepricingDetail(d) BEFORE curPriceUserRepricingDetail

;
EXTEND DESIGN userRepricing{
    PROPERTY(manufacturingPriceUserRepricingDetail) { background = #FFFFCC; }
}

EXTEND FORM repricings
    PROPERTIES(d) READONLY manufacturingPriceRepricingDetail BEFORE priceRepricingDetail, curManufacturingPriceRepricingDetail BEFORE curPriceRepricingDetail
;

overChangePriceUserRepricing(userRepricingDetail) += ACTION (userRepricingDetail) {
    SET manufacturingPriceUserRepricingDetail(userRepricingDetail) <- curManufacturingPriceUserRepricingDetail(userRepricingDetail);
}

