MODULE PurchaseInvoiceGeneralLedger;

REQUIRE GeneralLedger, PurchaseInvoice, DimensionLegalEntity, DimensionStock;

NAMESPACE Purchase;

//------------------- Приход товара/тары от поставщ. --------------------//

EXTEND CLASS Invoice : GeneralLedger.GLDocument;
nameGLDocument(document) += descriptionInvoice(document);
numberGLDocument(document) += numberInvoice(document);
seriesGLDocument(document) += seriesInvoice(document);
//editGLDocument (GLDocument)+= editInvoice(GLDocument);

//-------------------------------- НДС поставщика ----------------------------------//
//-- Тара
@defineGeneralLedgerAggregationOperation (invoice,                                      // основание
                                          InvSupVATC,                                   // идентификатор
                                          customer,                                     // компания
                                          VATSumContainerInvoiceDetailInvoice,          // сумма
                                          description,                                  // описание
                                          '18.5',                                       // дебет
                                          '60.1',                                       // кредит
                                          'by_default',                                 // идентификатор плана счетов
                                          'by_default_purchase_invoice'                         // идентификатор операции
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += customerStockInvoice(invoiceInvSupVATCGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupVATCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += supplierInvoice(invoiceInvSupVATCGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupVATCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization;
//-- Услуги
@defineGeneralLedgerAggregationOperation (invoice,
                                          InvSupVATCH,
                                          customer,
                                          VATSumChargeInvoiceDetailInvoice,
                                          description,
                                          '18.6',
                                          '60.1',
                                          'by_default',
                                          'by_default_purchase_invoice'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += customerStockInvoice(invoiceInvSupVATCHGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupVATCHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += supplierInvoice(invoiceInvSupVATCHGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupVATCHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization;
//-- Товар
@defineGeneralLedgerAggregationOperation (invoice,
                                          InvSupVATI,
                                          customer,
                                          VATSumItemInvoiceDetailInvoice,
                                          description,
                                          '18.1',
                                          '60.1',
                                          'by_default',
                                          'by_default_purchase_invoice'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += customerStockInvoice(invoiceInvSupVATIGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupVATIGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += supplierInvoice(invoiceInvSupVATIGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupVATIGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization;

//-------------------------------- Сумма поставщика ----------------------------------//
//-- Тара
@defineGeneralLedgerAggregationOperation (invoice,
                                          InvSupC,
                                          customer,
                                          sumContainerInvoiceDetailInvoice,
                                          description,
                                          '41.3',
                                          '60.1',
                                          'by_default',
                                          'by_default_purchase_invoice'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += customerStockInvoice(invoiceInvSupCGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += supplierInvoice(invoiceInvSupCGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization;
//-- Товар
@defineGeneralLedgerAggregationOperation (invoice,
                                          InvSupIH,
                                          customer,
                                          sumItemInvoiceDetailInvoice,
                                          description,
                                          '41.2',
                                          '60.1',
                                          'by_default',
                                          'by_default_purchase_invoice'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += customerStockInvoice(invoiceInvSupIHGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupIHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += supplierInvoice(invoiceInvSupIHGeneralLedger(generalLedger)) WHEN CLASS(invoiceInvSupIHGeneralLedger(generalLedger)) AND dimensionType == DimensionType.organization;

// ----------------------------------- Стандартные данные ----------------------------------- //

@defineLoadDefaultOperation (Purchase, iname, isid);
loadDefaultOperationsPurchaseInvoiceBy 'Загрузить стандарные операции прихода товара' () = ACTION () {
    EXEC loadDefaultOperation ('Приход товара от поставщика', 'by_default_purchase_invoice');
} ;

loadDefaultOperations () += loadDefaultOperationsPurchaseInvoiceBy();
