MODULE SalePurchaseShipmentGeneralLedger;

REQUIRE GeneralLedger, SalePurchaseShipment, DimensionStock;

NAMESPACE Sale;

//------------------- Внутреннее перемещение  --------------------//

EXTEND CLASS Shipment : GeneralLedger.GLDocument;
nameGLDocument(document) += descriptionShipment(document);
numberGLDocument(document) += numberShipment(document);
seriesGLDocument(document) += seriesShipment(document);
//editGLDocument (GLDocument)+= editInvoice(GLDocument);

////////////////////////////// Внутреннее перемещение (магазин-магазин) //////////////////////////////////
//-------------------------------- Розничная сумма ----------------------------------//
//-- Тара
@defineGeneralLedgerAggregationOperation (shipment,                                // основание
                                          ShipRetC,                                // идентификатор
                                          supplier,                                // компания
                                          sumContainerShipmentDetailShipment,      // сумма
                                          description,                             // описание
                                          '41.3',                                  // дебет
                                          '41.3',                                  // кредит
                                          'by_default',                            // идентификатор плана счетов
                                          'by_default_sale_shipment_retail'         // идентификатор операции
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += customerStockShipment(shipmentShipRetCGeneralLedger(generalLedger)) WHEN CLASS(shipmentShipRetCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += supplierStockShipment(shipmentShipRetCGeneralLedger(generalLedger)) WHEN CLASS(shipmentShipRetCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;

//-- Не тара
@defineGeneralLedgerAggregationOperation (shipment,
                                          ShipRetNotC,
                                          supplier,
                                          sumNotContainerShipmentDetailShipment,
                                          description,
                                          '41.2',
                                          '41.2',
                                          'by_default',
                                          'by_default_sale_shipment_retail'
                                          );
debitGeneralLedgerDimensionType(generalLedger,dimensionType) += customerStockShipment(shipmentShipRetNotCGeneralLedger(generalLedger)) WHEN CLASS(shipmentShipRetNotCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;
creditGeneralLedgerDimensionType(generalLedger,dimensionType) += supplierStockShipment(shipmentShipRetNotCGeneralLedger(generalLedger)) WHEN CLASS(shipmentShipRetNotCGeneralLedger(generalLedger)) AND dimensionType == DimensionType.stock;

// ----------------------------------- Стандартные данные ----------------------------------- //

@defineLoadDefaultOperationPrefix (Sale, iname, isid, sale);

loadDefaultOperationsSalePurchaseRetailBy 'Загрузить стандарные операции внутреннего перемещения м/ду магазинами' () = ACTION () {
    EXEC loadDefaultSaleOperation ('Перемещение между собственными магазинами', 'by_default_sale_shipment_retail');
} ;

loadDefaultOperations () += loadDefaultOperationsSalePurchaseRetailBy();