MODULE ImportVetraz;

REQUIRE Import;


//---------------------------------------------- Импорт данных -----------------------------------------------------//

GROUP vetrazGroup 'Ветразь' : public;

importVetrazDataAction 'Импортировать данные (Ветразь)' = ACTION CUSTOM 'fdk.region.by.integration.vetraz.ImportVetrazActionProperty' IN vetrazGroup;
importVetrazDirectory 'Папка' = DATA STRING[200] () IN vetrazGroup;
importItems 'Импортировать товары' = DATA BOOLEAN() IN vetrazGroup;
importNumberItems 'Кол-во' = DATA INTEGER () IN vetrazGroup;
importLegalEntities 'Импортировать организации' = DATA BOOLEAN() IN vetrazGroup;
importWarehouses 'Импортировать склады' = DATA BOOLEAN() IN vetrazGroup;
importUserInvoices 'Импортировать остатки' = DATA BOOLEAN() IN vetrazGroup;
importNumberUserInvoices 'Кол-во' = DATA INTEGER () IN vetrazGroup;

EXTEND FORM integrationData
    PROPERTIES() importVetrazDataAction, importVetrazDirectory, importItems, importNumberItems, importLegalEntities,
                 importWarehouses, importUserInvoices, importNumberUserInvoices
;
EXTEND DESIGN integrationData {
    pane {
        NEW vetraz {
            title = 'Ветразь';
            ADD NOGROUP.vetrazGroup;
        }
    }
}
