MODULE RepricingOperation;

REQUIRE Operation, LegalEntity, PriceListCalc;

NAMESPACE Repricing;

@defineOperation(' (переоценка)');

//@defineOperationPriceListType();

@defineOperationRole();
@extendFormFilterRole(o, dialogOperations);
//@extendFormFilterRole(o, operations);     //-- пока не нужен

priceListTypeOperation = DATA PriceListType (Operation);
namePriceListTypeOperation 'Вид цен (управленческий)' (operation) = namePriceListType(priceListTypeOperation(operation));

calcPriceListTypeOperation = DATA CalcPriceListType (Operation);
nameCalcPriceListTypeOperation 'Вид цен (надбавка)' (operation) = namePriceListType(calcPriceListTypeOperation(operation));

EXTEND FORM operation
    PROPERTIES(o) namePriceListTypeOperation, nameCalcPriceListTypeOperation
;
EXTEND DESIGN operation{
    tabContainer {
        NEW createContainer {
            caption = 'Производные документы';
        }
        NEW showContainer {
            caption = 'Отображение свойств';
            ADD PROPERTY(namePriceListTypeOperation);
            ADD PROPERTY(nameCalcPriceListTypeOperation);
        }
    }
}


