MODULE PricingTaxReverse;

REQUIRE TaxReverse, Pricing;

NAMESPACE Pricing;

overValueRetailVATUserPricingDetail(detail) += valueRateRangeDate(retailVATUserPricingDetail(detail), dateUserPricingDetail(detail)) * 100 /
                                    (100-valueRateRangeDate(retailVATUserPricingDetail(detail), dateUserPricingDetail(detail)))
                                    IF reverseRange(retailVATUserPricingDetail(detail));

