MODULE ContractLedger;

REQUIRE Contract,
        Document,
        LegalEntity,
        Numerator,
        Currency;

PRIORITY Contract;

META defineContractLedgerPrefix (caption, prefix)

    CLASS ABSTRACT contract###prefix##Ledger caption;
    TABLE contract###prefix##Ledger(contract###prefix##Ledger);

    isPostedContract###prefix##Ledger 'Закрыт' (contract###prefix##Ledger) = ABSTRACT BOOLEAN (contract###prefix##Ledger) PERSISTENT;

    dateTimeContract###prefix##Ledger 'Дата/время' (contract###prefix##Ledger) = ABSTRACT DATETIME (contract###prefix##Ledger) PERSISTENT;
    dateContract###prefix##Ledger 'Дата' (contract###prefix##Ledger) = dateInTime(dateTimeContract###prefix##Ledger(contract###prefix##Ledger));
    timeContract###prefix##Ledger 'Время' (contract###prefix##Ledger) = timeInDateTime(dateTimeContract###prefix##Ledger(contract###prefix##Ledger));

    contractContract###prefix##Ledger 'Договор' (contract###prefix##Ledger) = ABSTRACT contract (contract###prefix##Ledger) PERSISTENT;

    descriptionContract###prefix##Ledger 'Название документа' (contract###prefix##Ledger) = ABSTRACT STRING[200] (contract###prefix##Ledger) PERSISTENT;

    sumContract###prefix##Ledger 'Сумма' (contract###prefix##Ledger) = ABSTRACT NUMERIC[16,2] (contract###prefix##Ledger) PERSISTENT;

    currentBalance###prefix##Contract 'Текущая сумма задолженности по договору' (contract)=
        GROUP SUM sumContract###prefix##Ledger(contract###prefix##Ledger) AND isPostedContract###prefix##Ledger(contract###prefix##Ledger)
              BY contractContract###prefix##Ledger(contract###prefix##Ledger) PERSISTENT;

    balanceB###prefix##ContractDate 'Сумма задолженности по договору на дату (до)' (contract, date) =
        (currentBalance###prefix##Contract(contract) AND date AS DATE) (-)
        [GROUP SUM sumContract###prefix##Ledger(contract###prefix##Ledger) AND isPostedContract###prefix##Ledger(contract###prefix##Ledger)
                  IF dateContract###prefix##Ledger(contract###prefix##Ledger) >= (date AS DATE)
              BY contractContract###prefix##Ledger(contract###prefix##Ledger), date](contract, date);

    balanceA###prefix##ContractDate 'Сумма задолженности по договору на дату (после)' (contract, date) =
        (currentBalance###prefix##Contract(contract) AND date AS DATE) (-)
        [GROUP SUM sumContract###prefix##Ledger(contract###prefix##Ledger) AND isPostedContract###prefix##Ledger(contract###prefix##Ledger)
                  IF dateContract###prefix##Ledger(contract###prefix##Ledger) > (date AS DATE)
              BY contractContract###prefix##Ledger(contract###prefix##Ledger), date](contract, date);

END

@defineContractLedgerPrefix('Изменение управленческого долга по контракту', );
@defineContractLedgerPrefix('Изменение бухгалтерского долга по контракту', a);

META implementContractLedger(prefix, object)

    isPostedContract###prefix##Ledger(contract###prefix##Ledger) += isPosted###object(contract###prefix##Ledger);
    dateTimeContract###prefix##Ledger(contract###prefix##Ledger) += dateTime###object(contract###prefix##Ledger) IF isPostedContract###prefix##Ledger(contract###prefix##Ledger);
    contractContract###prefix##Ledger(contract###prefix##Ledger) += contract###object(contract###prefix##Ledger) IF isPostedContract###prefix##Ledger(contract###prefix##Ledger);
    descriptionContract###prefix##Ledger(contract###prefix##Ledger) += description###object(contract###prefix##Ledger) IF isPostedContract###prefix##Ledger(contract###prefix##Ledger);

END

META implementContractPrepaymentLedger(object, sumProp)

    CLASS object##ContractLedger : contractLedger;
    //TABLE object##ContractLedger(object##ContractLedger);

    needToCreate###object##ContractLedger (object, paymentPeriod) =
        isSaleTypePrepaymentFormPaymentCondition(paymentConditionContractDate(contract###object(object), date###object(object))) AND
        contract###object(object) == contractPaymentCondition(paymentConditionPaymentPeriod(paymentPeriod)) AND
        isPosted###object(object);

    @defineAggregationDouble(object, paymentPeriod, object##ContractLedger, needToCreate###object##ContractLedger);

    isPostedContractLedger(object##ContractLedger) += isPosted###object(object###object##ContractLedger(object##ContractLedger));
    dateTimeContractLedger(object##ContractLedger) += sumDateTimeDay(dateTime###object(object###object##ContractLedger(object##ContractLedger)),
                                                                     countDaysPaymentPeriod(paymentPeriod###object##ContractLedger(object##ContractLedger)));
    contractContractLedger(object##ContractLedger) += contract###object(object###object##ContractLedger(object##ContractLedger));
    descriptionContractLedger(object##ContractLedger) += description###object(object###object##ContractLedger(object##ContractLedger));
    sumContractLedger(object##ContractLedger) +=
        sumProp(object###object##ContractLedger(object##ContractLedger)) * percentPaymentPeriod(paymentPeriod###object##ContractLedger(object##ContractLedger)) / 100.0;

END

//--------------------------------------------- Логика приходов и расходов ------------------------------------------------------//

META defineOutContractLedgerInContractLedgerPrefix(caption, prefix)

    CLASS ABSTRACT prefix##ContractLedger caption;
    TABLE prefix##ContractLedger(prefix##ContractLedger);

    isPosted###prefix##ContractLedger 'Закрыт' (prefix##ContractLedger) = ABSTRACT BOOLEAN (prefix##ContractLedger) PERSISTENT;

    dateTime###prefix##ContractLedger 'Дата/время' (prefix##ContractLedger) = ABSTRACT DATETIME (prefix##ContractLedger) PERSISTENT;
    date###prefix##ContractLedger 'Дата' (prefix##ContractLedger) = dateInTime(dateTime###prefix##ContractLedger(prefix##ContractLedger));
    time###prefix##ContractLedger 'Время' (prefix##ContractLedger) = timeInDateTime(dateTime###prefix##ContractLedger(prefix##ContractLedger));

    contract###prefix##ContractLedger 'Договор' (prefix##ContractLedger) = ABSTRACT contract (prefix##ContractLedger) PERSISTENT;

    paymentCondition###prefix##ContractLedger 'Условия оплаты' (prefix##ContractLedger) =
        paymentConditionContractDate(contract###prefix##ContractLedger(prefix##ContractLedger), date###prefix##ContractLedger(prefix##ContractLedger));

    description###prefix##ContractLedger 'Название документа' (prefix##ContractLedger) = ABSTRACT STRING[200] (prefix##ContractLedger) PERSISTENT;
    sum###prefix##ContractLedger 'Сумма' = ABSTRACT NUMERIC[16,2] (prefix##ContractLedger) PERSISTENT;

    is###prefix##ContractLedger (prefix##ContractLedger) = prefix##ContractLedger IS prefix##ContractLedger;

END

@defineOutContractLedgerInContractLedgerPrefix('Приход', in);
@defineOutContractLedgerInContractLedgerPrefix('Расход', out);

TABLE outContractLedgerInContractLedger (outContractLedger, inContractLedger);
costOutContractLedgerInContractLedger 'Оплачено из документа' (outContractLedger, inContractLedger) = DATA NUMERIC[16,2] (outContractLedger, inContractLedger) PERSISTENT;
costedOutContractLedgerInContractLedger 'Оплачено по документу' (inContractLedger) =
    GROUP SUM costOutContractLedgerInContractLedger(outContractLedger, inContractLedger) AND
    isPostedInContractLedger(inContractLedger) AND isPostedOutContractLedger(outContractLedger)
    BY inContractLedger PERSISTENT;
costedOutContractLedgerInContractLedgerDate 'Оплачено по документу на дату' (inContractLedger, date) =
    GROUP SUM costOutContractLedgerInContractLedger(outContractLedger, inContractLedger) AND
              isPostedInContractLedger(inContractLedger) AND isPostedOutContractLedger(outContractLedger) AND
              dateOutContractLedger(outContractLedger) <= (date AS DATE)
    BY inContractLedger, date;
costedInContractLedgerOutContractLedger 'Расписано из документа' (outContractLedger) =
    GROUP SUM costOutContractLedgerInContractLedger(outContractLedger, inContractLedger) AND
    isPostedInContractLedger(inContractLedger) AND isPostedOutContractLedger(outContractLedger)
    BY outContractLedger PERSISTENT;
costedInContractLedgerOutContractLedgerDate 'Расписано из документа на дату' (outContractLedger, date) =
    GROUP SUM costOutContractLedgerInContractLedger(outContractLedger, inContractLedger) AND
              isPostedInContractLedger(inContractLedger) AND isPostedOutContractLedger(outContractLedger) AND
              dateInContractLedger(inContractLedger) <= (date AS DATE)
    BY outContractLedger, date;

debtInContractLedger 'Долг по документу' (inContractLedger) =
    sumInContractLedger(inContractLedger) (-) costedOutContractLedgerInContractLedger(inContractLedger) IF isPostedInContractLedger(inContractLedger) PERSISTENT;

debtInContractLedgerDate 'Долг по документу на дату' (inContractLedger, date) =
    sumInContractLedger(inContractLedger) (-) costedOutContractLedgerInContractLedgerDate(inContractLedger, date) IF isPostedInContractLedger(inContractLedger);

appliedInContractLedgerBonusPeriod(inContractLedger, bonusPeriod) =
    debtInContractLedgerDate(inContractLedger, sumDate(dateInContractLedger(inContractLedger), countDaysBonusPeriod(bonusPeriod))) <= 0.0
    AND contractInContractLedger(inContractLedger) == contractPaymentCondition(paymentConditionBonusPeriod(bonusPeriod));

daysBonusPeriodInContractLedger(inContractLedger, date) =
    GROUP MIN countDaysBonusPeriod(bonusPeriod) AND
              contractInContractLedger(inContractLedger) == contractPaymentCondition(paymentConditionBonusPeriod(bonusPeriod)) AND
              sumDate(dateInContractLedger(inContractLedger), countDaysBonusPeriod(bonusPeriod)) >= (date AS DATE)
              //appliedInContractLedgerBonusPeriod(inContractLedger, bonusPeriod)
    BY inContractLedger, date;

bonusPeriodInContractLedger(inContractLedger, date) =
    bonusPeriodPaymentConditionDays(paymentConditionInContractLedger(inContractLedger), daysBonusPeriodInContractLedger(inContractLedger, date));

bonusSumInContractLedger 'Сумма бонуса' (inContractLedger, date) =
    sumInContractLedger(inContractLedger) * percentBonusPeriod(bonusPeriodInContractLedger(inContractLedger, date))/100
    IF debtInContractLedger(inContractLedger) > 0.0;

bonusDebtSumInContractLedgerDate 'Сумма долга по документу с учетом бонуса' (inContractLedger, date) =
    debtInContractLedgerDate(inContractLedger, date) (-) bonusSumInContractLedger(inContractLedger, date);

CONSTRAINT costedInContractLedgerOutContractLedger(outContractLedger) > sumOutContractLedger(outContractLedger)
    MESSAGE 'Расписанная сумма должна быть равна сумме платежа';

orderInContractLedger(inContractLedger) = LIST(dateTimeInContractLedger(inContractLedger), inContractLedger);

sumInFIFOOutContractLedgerInContractLedger (outContractLedger, inContractLedger) =
    PARTITION UNGROUP sumOutContractLedger
              LIMIT debtInContractLedger(inContractLedger) AND
                    contractOutContractLedger(outContractLedger) == contractInContractLedger(inContractLedger) AND
                    isPostedInContractLedger(inContractLedger) AND isPostedOutContractLedger(outContractLedger)
              BY outContractLedger
              ORDER orderInContractLedger(inContractLedger);

sumInLIFOOutContractLedgerInContractLedger (outContractLedger, inContractLedger) =
    PARTITION UNGROUP sumOutContractLedger
              LIMIT debtInContractLedger(inContractLedger) AND (outContractLedger IS outContractLedger) AND
                    contractOutContractLedger(outContractLedger) == contractInContractLedger(inContractLedger) AND
                    isPostedInContractLedger(inContractLedger) AND isPostedOutContractLedger(outContractLedger)
              BY outContractLedger
              ORDER DESC orderInContractLedger(inContractLedger);

writeOutContractLedgerFIFO 'Расписать по FIFO' = ACTION (outContractLedger) {

    SET costOutContractLedgerInContractLedger(outContractLedger, inContractLedger) <- NULL;
    SET costOutContractLedgerInContractLedger(outContractLedger, inContractLedger) <- sumInFIFOOutContractLedgerInContractLedger(outContractLedger, inContractLedger);
}

writeOutContractLedgerLIFO 'Расписать по LIFO' = ACTION (outContractLedger) {

    SET costOutContractLedgerInContractLedger(outContractLedger, inContractLedger) <- NULL;
    SET costOutContractLedgerInContractLedger(outContractLedger, inContractLedger) <- sumInLIFOOutContractLedgerInContractLedger(outContractLedger, inContractLedger);
}

META implementOutContractLedgerInContractLedgerPrefix(prefix, object)

    isPosted###prefix##ContractLedger(prefix##ContractLedger) += isPosted###object(prefix##ContractLedger);
    dateTime###prefix##ContractLedger(prefix##ContractLedger) += dateTime###object(prefix##ContractLedger) IF isPosted###prefix##ContractLedger(prefix##ContractLedger);
    contract###prefix##ContractLedger(prefix##ContractLedger) += contract###object(prefix##ContractLedger) IF isPosted###prefix##ContractLedger(prefix##ContractLedger);
    description###prefix##ContractLedger(prefix##ContractLedger) += description###object(prefix##ContractLedger) IF isPosted###prefix##ContractLedger(prefix##ContractLedger);

END

//-------------------------------------------- Логика платежей ----------------------------------------------------------------//

CLASS payment 'Платеж' : numeratedObject, contractLedger, contractALedger, outContractLedger;
CLASS paymentPosted 'Закрытый платеж' : payment, postedObject;
TABLE payment(payment);

@defineDocumentHeaderPosted(payment);
@defineNumeratedObject(payment, 'Нумератор для платежей', 'ПЛ');

datePayment 'Дата' (payment) = DATA DATE (payment) PERSISTENT;
datePayment(payment) <- currentDate() WHEN ASSIGNED(payment IS payment);
timePayment 'Время' (payment) = DATA TIME (payment) PERSISTENT;
timePayment(payment) <- currentTime() WHEN ASSIGNED(payment IS payment);
dateTimePayment 'Дата время' (payment) = toDateTime(datePayment(payment), timePayment(payment));

contractPayment 'Контракт' (payment) = DATA contract (payment) AUTOSET  PERSISTENT;
numberContractPayment 'Номер контракта' (payment) = numberContract(contractPayment(payment));

notePayment 'Примечение' (payment) = DATA STRING[200] (payment) PERSISTENT;

payerPayment(payment) = DATA legalEntity (payment) PERSISTENT;
payerPayment(payment) <- partyBContract(contractPayment(payment)) WHEN ASSIGNED (contractPayment(payment));
namePayerPayment 'Сторона Б(Плательщик)' (payment) = name(payerPayment(payment));
beneficiaryPayment(payment) = DATA legalEntity (payment) PERSISTENT;
beneficiaryPayment(payment) <- partyAContract(contractPayment(payment)) WHEN ASSIGNED (contractPayment(payment));
nameBeneficiaryPayment 'Сторона А(Бенефициар)' (payment) = name(beneficiaryPayment(payment));

currencyPayment 'Валюта платежа' (payment) = DATA currency (payment) PERSISTENT;
nameCurrencyPayment 'Валюта платежа' (payment) = name(currencyPayment(payment));
typeExchangePayment (payment) = DATA typeExchange (payment) PERSISTENT;
nameTypeExchangePayment 'Тип обмена' (payment) = name(typeExchangePayment(payment));
rateExchangePayment 'Курс' (payment) = DATA NUMERIC[15,8] (payment) PERSISTENT;
rateExchangePayment (payment) <- UNION OVERRIDE 1.0 IF payment IS payment, rateTypeExchangeCurrencyDate(typeExchangePayment(payment), currencyPayment(payment), datePayment(payment))
    WHEN CHANGED (currencyPayment(payment)) OR
         CHANGED (typeExchangePayment(payment)) OR
         CHANGED (datePayment(payment));

CONSTRAINT currencyTypeExchange(typeExchangePayment(payment)) != currencyContract(contractPayment(payment))
    CHECKED BY typeExchangePayment MESSAGE 'Валюта типа обмена должны соответствовать валюте договора+';

sumPayment 'Сумма платежа' (payment) = DATA NUMERIC[16,2] (payment) PERSISTENT;
sumRateExchangePayment 'Сумма платежа(конверт.)' (payment) = sumPayment(payment) / rateExchangePayment(payment);

isNotSameCurrencyPayment (payment) = currencyContract(contractPayment(payment)) != currencyPayment(payment);

descriptionPayment 'Название документа' =
    [FORMULA STRING[200] '\'Платеж \' || CAST($1 AS TEXT) ||  \' от \' || CAST($2 AS TEXT) || \' \' || CAST($3 AS TEXT)'](
    seriesNumberObject(payment), datePayment(payment), nameBeneficiaryPayment(payment)) PERSISTENT;

@implementContractLedger( ,payment);
sumContractLedger(contractLedger) += -sumRateExchangePayment(contractLedger) IF isPostedPayment(contractLedger);

@implementContractLedger(a ,payment);
sumContractALedger(contractALedger) += -sumRateExchangePayment(contractALedger) IF isPostedPayment(contractALedger);

@implementOutContractLedgerInContractLedgerPrefix(out, payment);
sumOutContractLedger(outContractLedger) += sumRateExchangePayment(outContractLedger) IF isPostedPayment(outContractLedger);

FORM payment 'Платеж'

    OBJECTS p = payment FIXED PANEL, i = inContractLedger
    PROPERTIES(p) objectClassName, nameNumeratorObject, numberObject, seriesObject, datePayment, timePayment,
                  numberContractPayment, notePayment
    PROPERTIES(p) READONLY namePayerPayment, nameBeneficiaryPayment
    PROPERTIES(p) nameCurrencyPayment, nameTypeExchangePayment SHOWIF isNotSameCurrencyPayment(p), sumPayment,
                  rateExchangePayment SHOWIF isNotSameCurrencyPayment(p),
                  sumRateExchangePayment SHOWIF isNotSameCurrencyPayment(p),
                  costedInContractLedgerOutContractLedger,
                  writeOutContractLedgerFIFO TODRAW i FORCE PANEL,
                  writeOutContractLedgerLIFO TODRAW i FORCE PANEL

    PROPERTIES(i) READONLY descriptionInContractLedger, debtInContractLedger
    PROPERTIES(p, i) costOutContractLedgerInContractLedger

    FILTERS contractPayment(p) == contractInContractLedger(i)

    EVENTS
        ON OK EXEC prePostPayment(p)

    EDIT payment OBJECT p
;

DESIGN payment FROM DEFAULT{

    main{

        NEW headerContainer{

            caption = 'Шапка документа';
            childConstraints = TO THE RIGHT;
            ADD PROPERTY(objectClassName);
            ADD PROPERTY(namePayerPayment);
            ADD PROPERTY(nameNumeratorObject);
            ADD PROPERTY(numberObject);
            ADD PROPERTY(seriesObject);
            ADD PROPERTY(datePayment);
            ADD PROPERTY(timePayment);
        }

        NEW paramContainer {

            caption = 'Параметры документа';
            ADD PROPERTY(numberContractPayment);
            ADD PROPERTY(nameBeneficiaryPayment);
            ADD PROPERTY(notePayment);
        }

        NEW sumContainer{

            caption = 'Суммы документа';
            childConstraints = TO THE BOTTOM;
            ADD PROPERTY(sumPayment);
            ADD PROPERTY(nameCurrencyPayment);
            ADD PROPERTY(nameTypeExchangePayment);
            ADD PROPERTY(rateExchangePayment);
            ADD PROPERTY(sumRateExchangePayment);
            ADD PROPERTY(costedInContractLedgerOutContractLedger);
        }
        POSITION sumContainer TO THE RIGHT headerContainer;
        POSITION sumContainer TO THE RIGHT paramContainer;

        ADD i.box;
    }

    PROPERTY (writeOutContractLedgerFIFO(p)){panelLocation = TOOLBAR;}
    PROPERTY (writeOutContractLedgerLIFO(p)){panelLocation = TOOLBAR;}
    POSITION PROPERTY(writeOutContractLedgerLIFO) TO THE RIGHT PROPERTY(writeOutContractLedgerFIFO);

    PROPERTY(formOkAction) {
        caption = 'Провести';
    }

    ADD functions.box;
}

partyA = SESSION DATA legalEntity();
namePartyA 'Сторона А' = name(partyA());
partyB = SESSION DATA legalEntity();
namePartyB 'Сторона Б' = name(partyB());

//--------------------------------------------- Платежное требование ------------------------------------------------------//

CLASS paymentRequest 'Платежное требование' : numeratedObject, contractLedger, inContractLedger;
CLASS paymentRequestPosted 'Закрытое платежное требование' : paymentRequest, postedObject;
TABLE paymentRequest(paymentRequest);

@defineDocumentHeaderPosted(paymentRequest);
@defineNumeratedObject(paymentRequest, 'Нумератор для платежных требований', 'ПТ');

datePaymentRequest 'Дата' (paymentRequest) = DATA DATE (paymentRequest) PERSISTENT;
datePaymentRequest(paymentRequest) <- currentDate() WHEN ASSIGNED(paymentRequest IS paymentRequest);
timePaymentRequest 'Время' (paymentRequest) = DATA TIME (paymentRequest) PERSISTENT;
timePaymentRequest(paymentRequest) <- currentTime() WHEN ASSIGNED(paymentRequest IS paymentRequest);
dateTimePaymentRequest 'Дата время' (paymentRequest) = toDateTime(datePaymentRequest(paymentRequest), timePaymentRequest(paymentRequest));

contractPaymentRequest 'Контракт' (paymentRequest) = DATA contract (paymentRequest) AUTOSET PERSISTENT;
numberContractPaymentRequest 'Номер контракта' (paymentRequest) = numberContract(contractPaymentRequest(paymentRequest));

notePaymentRequest 'Примечание' (paymentRequest) = DATA STRING[200] (paymentRequest) PERSISTENT;

payerPaymentRequest(paymentRequest) = DATA legalEntity (paymentRequest) PERSISTENT;
payerPaymentRequest(paymentRequest) <- partyBContract(contractPaymentRequest(paymentRequest)) WHEN ASSIGNED (contractPaymentRequest(paymentRequest));
namePayerPaymentRequest 'Сторона Б' (paymentRequest) = name(payerPaymentRequest(paymentRequest));
lenderPaymentRequest(paymentRequest) = DATA legalEntity (paymentRequest) PERSISTENT;
lenderPaymentRequest(paymentRequest) <- partyAContract(contractPaymentRequest(paymentRequest)) WHEN ASSIGNED (contractPaymentRequest(paymentRequest));
nameLenderPaymentRequest 'Сторона А' (paymentRequest) = name(lenderPaymentRequest(paymentRequest));

sumPaymentRequest 'Сумма' (paymentRequest) = DATA NUMERIC[16,2] (paymentRequest) PERSISTENT;

descriptionPaymentRequest 'Название документа' =
    [FORMULA STRING[200] '\'Платежное требование \' || CAST($1 AS TEXT) ||  \' от \' || CAST($2 AS TEXT) || \' \' || CAST($3 AS TEXT)'](
    seriesNumberObject(paymentRequest), datePaymentRequest(paymentRequest), nameLenderPaymentRequest(paymentRequest)) PERSISTENT;

@implementContractLedger( ,paymentRequest);
sumContractLedger(contractLedger) += sumPaymentRequest(contractLedger) IF isPostedPaymentRequest(contractLedger);

FORM paymentRequest 'Платежное требование'

    OBJECTS p = paymentRequest FIXED PANEL
    PROPERTIES(p) objectClassName, nameNumeratorObject, numberObject, seriesObject, datePaymentRequest, timePaymentRequest,
                  numberContractPaymentRequest, notePaymentRequest
    PROPERTIES(p) READONLY namePayerPaymentRequest, nameLenderPaymentRequest
    PROPERTIES(p) sumPaymentRequest

    EVENTS
        ON OK EXEC prePostPaymentRequest(p)

    EDIT paymentRequest OBJECT p
;

DESIGN paymentRequest FROM DEFAULT{

    main{

        NEW headerContainer{

            caption = 'Шапка документа';
            childConstraints = TO THE RIGHT;
            ADD PROPERTY(objectClassName);
            ADD PROPERTY(namePayerPaymentRequest);
            ADD PROPERTY(nameNumeratorObject);
            ADD PROPERTY(numberObject);
            ADD PROPERTY(seriesObject);
            ADD PROPERTY(datePaymentRequest);
            ADD PROPERTY(timePaymentRequest);
        }

        NEW paramContainer {

            caption = 'Параметры документа';
            ADD PROPERTY(numberContractPaymentRequest);
            ADD PROPERTY(nameLenderPaymentRequest);
            ADD PROPERTY(notePaymentRequest);
        }

        NEW sumContainer{

            caption = 'Суммы документа';
            childConstraints = TO THE BOTTOM;
            ADD PROPERTY(sumPaymentRequest);
        }
        POSITION sumContainer TO THE RIGHT headerContainer;
        POSITION sumContainer TO THE RIGHT paramContainer;
    }

    PROPERTY(formOkAction) {
        caption = 'Провести';
    }

    ADD functions.box;
}

//-------------------------------------------- Кредитная нота --------------------------------------------------------//

CLASS ABSTRACT creditMemo 'Кредитная нота' : numeratedObject;
TABLE creditMemo(creditMemo);

META defineCreditMemoPrefix(prefix, caption, captionPost)

    CLASS creditMemo###prefix caption : creditMemo, contractLedger, contractALedger, prefix##ContractLedger;
    CLASS creditMemo###prefix##Posted  captionPost : creditMemo###prefix, postedObject;

    @defineDocumentHeaderPosted(creditMemo###prefix);
    @defineNumeratedObject(creditMemo###prefix, 'Нумератор для кредитных нот', 'КН');

    dateCreditMemo###prefix 'Дата' (creditMemo###prefix) = DATA DATE (creditMemo###prefix) PERSISTENT;
    dateCreditMemo###prefix(creditMemo###prefix) <- currentDate() WHEN ASSIGNED(creditMemo###prefix IS creditMemo###prefix);
    timeCreditMemo###prefix 'Время' (creditMemo###prefix) = DATA TIME (creditMemo###prefix) PERSISTENT;
    timeCreditMemo###prefix(creditMemo###prefix) <- currentTime() WHEN ASSIGNED(creditMemo###prefix IS creditMemo###prefix);
    dateTimeCreditMemo###prefix 'Дата время' (creditMemo###prefix) = toDateTime(dateCreditMemo###prefix(creditMemo###prefix), timeCreditMemo###prefix(creditMemo###prefix));

    contractCreditMemo###prefix 'Контракт' (creditMemo###prefix) = DATA contract (creditMemo###prefix) AUTOSET PERSISTENT;
    numberContractCreditMemo###prefix 'Номер контракта' (creditMemo###prefix) = numberContract(contractCreditMemo###prefix(creditMemo###prefix));

    noteCreditMemo###prefix 'Примечание' (creditMemo###prefix) = DATA STRING[200] (creditMemo###prefix) PERSISTENT;

    partyBCreditMemo###prefix(creditMemo###prefix) = DATA legalEntity (creditMemo###prefix) PERSISTENT;
    partyBCreditMemo###prefix(creditMemo###prefix) <- partyBContract(contractCreditMemo###prefix(creditMemo###prefix))
        WHEN ASSIGNED (contractCreditMemo###prefix(creditMemo###prefix));
    namePartyBCreditMemo###prefix 'Сторона Б' (creditMemo###prefix) = name(partyBCreditMemo###prefix(creditMemo###prefix));
    partyACreditMemo###prefix(creditMemo###prefix) = DATA legalEntity (creditMemo###prefix) PERSISTENT;
    partyACreditMemo###prefix(creditMemo###prefix) <- partyAContract(contractCreditMemo###prefix(creditMemo###prefix))
        WHEN ASSIGNED (contractCreditMemo###prefix(creditMemo###prefix));
    namePartyACreditMemo###prefix 'Сторона А' (creditMemo###prefix) = name(partyACreditMemo###prefix(creditMemo###prefix));

    sumCreditMemo###prefix 'Сумма' (creditMemo###prefix) = DATA NUMERIC[16,2] (creditMemo###prefix) PERSISTENT;

    descriptionCreditMemo###prefix 'Название документа' =
        [FORMULA STRING[200] '\''###caption###' \' || CAST($1 AS TEXT) ||  \' от \' || CAST($2 AS TEXT) || \' \' || CAST($3 AS TEXT)'](
        seriesNumberObject(creditMemo###prefix), dateCreditMemo###prefix(creditMemo###prefix), namePartyACreditMemo###prefix(creditMemo###prefix)) PERSISTENT;

END

META defineCreditMemoUnion (prop, caption)

    prop##CreditMemo caption (creditMemo) = UNION EXCLUSIVE prop##CreditMemoIn(creditMemo), prop##CreditMemoOut(creditMemo);

END

@defineCreditMemoPrefix(in, 'Кредитная нота', 'Закрытая кредитная нота');
@defineCreditMemoPrefix(out, 'Дебетная нота', 'Закрытая дебитовая нота');

prePostCreditMemo 'Провести' (creditMemo) = ABSTRACT ACTION(creditMemo);
prePostCreditMemo(creditMemo) += prePostCreditMemoIn(creditMemo);
prePostCreditMemo(creditMemo) += prePostCreditMemoOut(creditMemo);

@defineCreditMemoUnion(date, 'Дата');
@defineCreditMemoUnion(time, 'Время');
dateTimeCreditMemo 'Дата/время' (creditMemo) = toDateTime(dateCreditMemo(creditMemo), timeCreditMemo(creditMemo));
@defineCreditMemoUnion(contract, 'Контракт');
numberContractCreditMemo 'Номер контракта' (creditMemo) = numberContract(contractCreditMemo(creditMemo));
@defineCreditMemoUnion(partyB, );
namePartyBCreditMemo 'Сторона Б' (creditMemo) = name(partyBCreditMemo(creditMemo));
@defineCreditMemoUnion(partyA, );
namePartyACreditMemo 'Сторона А' (creditMemo) = name(partyACreditMemo(creditMemo));
@defineCreditMemoUnion(sum, 'Сумма');
@defineCreditMemoUnion(description, 'Название документа');
@defineCreditMemoUnion(note, 'Примечание');

@implementContractLedger( ,creditMemoIn);
sumContractLedger(contractLedger) += sumCreditMemoIn(contractLedger) IF isPostedCreditMemoIn(contractLedger);

@implementContractLedger(a ,creditMemoIn);
sumContractALedger(contractALedger) += sumCreditMemoIn(contractALedger) IF isPostedCreditMemoIn(contractALedger);

@implementOutContractLedgerInContractLedgerPrefix(in, creditMemoIn);
sumInContractLedger(inContractLedger) += sumCreditMemoIn(inContractLedger) IF isPostedCreditMemoIn(inContractLedger);

@implementContractLedger( ,creditMemoOut);
sumContractLedger(contractLedger) += -sumCreditMemoOut(contractLedger IF isPostedCreditMemoOut(contractLedger));

@implementContractLedger(a ,creditMemoOut);
sumContractALedger(contractALedger) += -sumCreditMemoOut(contractALedger) IF isPostedCreditMemoOut(contractALedger);

@implementOutContractLedgerInContractLedgerPrefix(out, creditMemoOut);
sumOutContractLedger(outContractLedger) += sumCreditMemoOut(outContractLedger) IF isPostedCreditMemoOut(outContractLedger);

FORM creditMemo 'Кредитная нота'

    OBJECTS c = creditMemo FIXED PANEL, i = inContractLedger
    PROPERTIES(c) objectClassName, nameNumeratorObject, numberObject, seriesObject, dateCreditMemo, timeCreditMemo,
                  numberContractCreditMemo, noteCreditMemo
    PROPERTIES(c) READONLY namePartyBCreditMemo, namePartyACreditMemo
    PROPERTIES(c) sumCreditMemo,
                  costedInContractLedgerOutContractLedger SHOWIF isOutContractLedger(c),
                  writeOutContractLedgerFIFO TODRAW i FORCE PANEL SHOWIF isOutContractLedger(c),
                  writeOutContractLedgerLIFO TODRAW i FORCE PANEL SHOWIF isOutContractLedger(c)

    PROPERTIES(i) READONLY descriptionInContractLedger SHOWIF isOutContractLedger(c), debtInContractLedger SHOWIF isOutContractLedger(c)
    PROPERTIES(c, i) costOutContractLedgerInContractLedger SHOWIF isOutContractLedger(c)

    FILTERS contractCreditMemo(c) == contractInContractLedger(i)

    EVENTS
        ON OK EXEC prePostCreditMemo(c)

    EDIT creditMemo OBJECT c
;

DESIGN creditMemo FROM DEFAULT{

    main{

        NEW headerContainer{

            caption = 'Шапка документа';
            childConstraints = TO THE RIGHT;
            ADD PROPERTY(objectClassName);
            ADD PROPERTY(namePartyBCreditMemo);
            ADD PROPERTY(nameNumeratorObject);
            ADD PROPERTY(numberObject);
            ADD PROPERTY(seriesObject);
            ADD PROPERTY(dateCreditMemo);
            ADD PROPERTY(timeCreditMemo);
        }

        NEW paramContainer {

            caption = 'Параметры документа';
            ADD PROPERTY(numberContractCreditMemo);
            ADD PROPERTY(namePartyACreditMemo);
            ADD PROPERTY(noteCreditMemo);
        }

        NEW sumContainer{

            caption = 'Суммы документа';
            childConstraints = TO THE BOTTOM;
            ADD PROPERTY(sumCreditMemo);
            ADD PROPERTY(costedInContractLedgerOutContractLedger);
        }
        POSITION sumContainer TO THE RIGHT headerContainer;
        POSITION sumContainer TO THE RIGHT paramContainer;

        ADD i.box;
    }

    PROPERTY (writeOutContractLedgerFIFO(c)){panelLocation = TOOLBAR;}
    PROPERTY (writeOutContractLedgerLIFO(c)){panelLocation = TOOLBAR;}
    POSITION PROPERTY(writeOutContractLedgerLIFO) TO THE RIGHT PROPERTY(writeOutContractLedgerFIFO);

    PROPERTY(formOkAction) {
        caption = 'Провести';
    }

    ADD functions.box;
}

//------------------------------------------- Платеж по договору -----------------------------------------------------//

debtSumContractDate 'Долг по договору на дату' (contract, date) = GROUP SUM debtInContractLedgerDate(inContractLedger, date) AND
                                                                            dateInContractLedger(inContractLedger) <= (date AS DATE)
                                                                  BY contractInContractLedger(inContractLedger), date;

bonusSumContractDate 'Сумма бонуса на дату' (contract, date) = GROUP SUM bonusSumInContractLedger(inContractLedger, date) AND
                                                                         dateInContractLedger(inContractLedger) <= (date AS DATE)
                                                               BY contractInContractLedger(inContractLedger), date;

bonusDebtSumContractDate 'Сумма долга с учетом бонуса' (contract, date) =
    debtSumContractDate(contract, date) (-) bonusSumContractDate(contract, date);

payContractDate 'Оплатить по договору' = ACTION (contract, date) NEWSESSION {

    ADDOBJ payment;
    FOR pm == addedObject() DO {
        SET dateTimePayment(pm) <- timeDate(date AS DATE);
        SET contractPayment(pm) <- contract AS contract;
        SET currencyPayment(pm) <- currencyContract(contract);
        SET sumPayment(pm) <- debtSumContractDate(contract, date);
        SET costOutContractLedgerInContractLedger(pm, inContractLedger) <- debtInContractLedgerDate(inContractLedger, date)
            WHERE contractPayment(pm) == contractInContractLedger(inContractLedger);
        FORM payment OBJECTS p = pm MODAL;
        IF formResult() == formResult.ok THEN {
            EXEC apply();
        }
    }

}

//------------------------------------------- Платеж c учетом бонусов договора --------------------------------------------//

payPaymentConditionInContractLedgerDate 'Оплатить c учетом бонусов договора' = [ACTION (inContractLedger, date) NEWSESSION {

    ADDOBJ payment;
    FOR pm == addedObject() DO {
        SET dateTimePayment(pm) <- timeDate(date AS DATE);
        SET contractPayment(pm) <- contractInContractLedger(inContractLedger);
        SET currencyPayment(pm) <- currencyContract(contractInContractLedger(inContractLedger));
        SET sumPayment(pm) <- bonusDebtSumInContractLedgerDate(inContractLedger, date);
        SET costOutContractLedgerInContractLedger(pm, inContractLedger) <- bonusDebtSumInContractLedgerDate(inContractLedger, date);
        FORM payment OBJECTS p = pm MODAL;
        IF formResult() == formResult.ok THEN {
            ADDOBJ creditMemoOut;
            FOR cm == addedObject() DO {
                SET dateTimeCreditMemoOut(cm) <- timeDate(date AS DATE);
                SET contractCreditMemoOut(cm) <- contractInContractLedger(inContractLedger);
                SET sumCreditMemoOut(cm) <- bonusSumInContractLedger(inContractLedger, date);
                SET costOutContractLedgerInContractLedger(cm, inContractLedger) <- bonusSumInContractLedger(inContractLedger, date);
                FORM creditMemo OBJECTS c = cm MODAL;
                IF formResult() == formResult.ok THEN {
                    EXEC apply();
                }
            }
        }
    }
}](inContractLedger, date) AND bonusSumInContractLedger(inContractLedger, date) > 0.0;

payPaymentConditionContractDate 'Оплатить c учетом бонусов договора' = [ACTION (contract, date) NEWSESSION {

    ADDOBJ payment;
    FOR pm == addedObject() DO {
        SET dateTimePayment(pm) <- timeDate(date AS DATE);
        SET contractPayment(pm) <- contract AS contract;
        SET currencyPayment(pm) <- currencyContract(contract);
        SET sumPayment(pm) <- bonusDebtSumContractDate(contract, date);
        SET costOutContractLedgerInContractLedger(pm, inContractLedger) <- bonusDebtSumInContractLedgerDate(inContractLedger, date)
            WHERE contractPayment(pm) == contractInContractLedger(inContractLedger);
        FORM payment OBJECTS p = pm MODAL;
        IF formResult() == formResult.ok THEN {
            ADDOBJ creditMemoOut;
            FOR cm == addedObject() DO {
                SET dateTimeCreditMemoOut(cm) <- timeDate(date AS DATE);
                SET contractCreditMemoOut(cm) <- contract AS contract;
                SET sumCreditMemoOut(cm) <- bonusSumContractDate(contract, date);
                SET costOutContractLedgerInContractLedger(cm, inContractLedger) <- bonusSumInContractLedger(inContractLedger, date)
                    WHERE contractCreditMemo(cm) == contractInContractLedger(inContractLedger);
                FORM creditMemo OBJECTS c = cm MODAL;
                IF formResult() == formResult.ok THEN {
                    EXEC apply();
                }
            }
        }
    }

}](contract, date) AND bonusSumContractDate(contract, date) > 0.0;

//----------------------------------------------- Цвета --------------------------------------------------------------//

backgroundSumContractLedger 'Цвет' (contractLedger) = RGB(255,238,165) AND contractLedger IS contractLedger;
backgroundContractLedgerDate 'Цвет' (contractLedger, date) = RGB(255,160,160) AND dateContractLedger(contractLedger) > (date AS DATE);
backgroundSumContract 'Цвет' (contract) = RGB(255,238,165) AND contract IS contract;
backgroundSumContractALedger 'Цвет' (contractALedger) = RGB(232,184,146) AND contractALedger IS contractALedger;
backgroundContractALedgerDate 'Цвет' (contractALedger, date) = RGB(255,160,160) AND dateContractALedger(contractALedger) > (date AS DATE);
backgroundSumContractA 'Цвет' (contract) = RGB(232,184,146) AND contract IS contract;
backgroundBonusSumInContractLedger 'Цвет' (inContractLedger) = RGB(213,249,185) AND inContractLedger IS inContractLedger;
backgroundBonusSumContract 'Цвет' (contract) = RGB(213,249,185) AND contract IS contract;
backgroundPaymentRequestDate 'Цвет' (paymentRequest, date) = RGB(255,160,160) AND datePaymentRequest(paymentRequest) > (date AS DATE);
backgroundOutContractLedgerDate 'Цвет' (outContractLedger, date) = RGB(255,160,160) AND dateOutContractLedger(outContractLedger) > (date AS DATE);
backgroundInContractLedgerDate 'Цвет' (inContractLedger, date) = RGB(255,160,160) AND dateInContractLedger(inContractLedger) > (date AS DATE);

//-------------------------------------------- Форма платежей ---------------------------------------------------------//

FORM payments 'Платежи'

    OBJECTS d = DATE FIXED PANEL
    PROPERTIES(d) date = OBJVALUE

    PROPERTIES() namePartyA, namePartyB

    OBJECTS p = payment
    PROPERTIES(p) READONLY objectClassName BACKGROUND backgroundOutContractLedgerDate(p, d),
                           numberObject BACKGROUND backgroundOutContractLedgerDate(p, d),
                           seriesObject BACKGROUND backgroundOutContractLedgerDate(p, d),
                           dateTimePayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           numberContractPayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           namePayerPayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           nameBeneficiaryPayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           nameCurrencyPayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           nameTypeExchangePayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           sumPayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           rateExchangePayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           sumRateExchangePayment BACKGROUND backgroundOutContractLedgerDate(p, d),
                           notePayment BACKGROUND backgroundOutContractLedgerDate(p, d)

    PROPERTIES(p) ADDFORM, EDITFORM, delete

    FILTERS payerPayment(p) == partyB() OR (p IS payment AND NOT partyB()),
            beneficiaryPayment(p) == partyA() OR (p IS payment AND NOT partyA())

;

DESIGN payments FROM DEFAULT{

    NEW headerContainer {
        childConstraints = TO THE RIGHT;
        caption = 'Шапка';
        ADD PROPERTY(date);
        ADD PROPERTY(namePartyA);
        ADD PROPERTY(namePartyB);
    }
    ADD p.box;
    ADD functions.box;
}

//-------------------------------------------- Разнесение по документам -----------------------------------------------//

isCostedOutContractLedger 'Расписан' (outContractLedger) = sumOutContractLedger(outContractLedger) (-) costedInContractLedgerOutContractLedger(outContractLedger);

FORM writeOutContractLedger 'Разнесение документов'

    OBJECTS d = DATE FIXED PANEL
    PROPERTIES(d) date = OBJVALUE

    PROPERTIES() namePartyA, namePartyB

    OBJECTS o = outContractLedger, i = inContractLedger
    PROPERTIES(o) READONLY dateOutContractLedger BACKGROUND backgroundOutContractLedgerDate(o, d),
                           descriptionOutContractLedger BACKGROUND backgroundOutContractLedgerDate(o, d),
                           sumOutContractLedger BACKGROUND backgroundOutContractLedgerDate(o, d),
                           costedInContractLedgerOutContractLedger BACKGROUND backgroundOutContractLedgerDate(o, d)
    PROPERTIES(o) writeOutContractLedgerFIFO TODRAW i FORCE PANEL,
                  writeOutContractLedgerLIFO TODRAW i FORCE PANEL
    ORDER BY dateOutContractLedger

    PROPERTIES(i) READONLY dateInContractLedger BACKGROUND backgroundInContractLedgerDate(i, d),
                           descriptionInContractLedger BACKGROUND backgroundInContractLedgerDate(i, d),
                           debtInContractLedger BACKGROUND backgroundInContractLedgerDate(i, d)
    PROPERTIES(o, i) costOutContractLedgerInContractLedger BACKGROUND backgroundInContractLedgerDate(i, d)
    ORDER BY dateInContractLedger

    FILTERGROUP filters1
        FILTER 'Неразнесенные' 'F9' isCostedOutContractLedger(o) DEFAULT

    FILTERGROUP filters2
        FILTER 'Неоплаченные' 'F10' debtInContractLedger(i) DEFAULT

    FILTERS partyBContract(contractOutContractLedger(o)) == partyB() OR (o IS outContractLedger AND NOT partyB()),
            partyAContract(contractOutContractLedger(o)) == partyA() OR (o IS outContractLedger AND NOT partyA()),
            contractOutContractLedger(o) == contractInContractLedger(i)

;

DESIGN writeOutContractLedger FROM DEFAULT {

    NEW topContainer {

        childConstraints = TO THE BOTTOM;
        NEW headerContainer {
            childConstraints = TO THE RIGHT;
            caption = 'Шапка';
            ADD PROPERTY(date);
            ADD PROPERTY(namePartyA);
            ADD PROPERTY(namePartyB);
        }
        NEW firstContainer {

            type = SPLITV;
            ADD o.box;
            ADD i.box{
                PROPERTY (writeOutContractLedgerFIFO(o)){panelLocation = TOOLBAR;}
                PROPERTY (writeOutContractLedgerLIFO(o)){panelLocation = TOOLBAR;}
            }
        }
   }

ADD functions.box;
}

//-------------------------------------------- Сводная форма ---------------------------------------------------------//

FORM contractLedger 'Управление задолженностями'

    OBJECTS d = DATE FIXED PANEL
    PROPERTIES(d) date = OBJVALUE

    PROPERTIES() namePartyA, namePartyB

    OBJECTS c = contract
    PROPERTIES(c) READONLY numberContract, namePartyAContract, namePartyBContract, nameCurrencyContract
    PROPERTIES(c, d) READONLY balanceAContractDate BACKGROUND backgroundSumContract(c),
                              balanceAAContractDate BACKGROUND backgroundSumContractA(c),
                              debtSumContractDate BACKGROUND backgroundBonusSumContract(c),
                              bonusSumContractDate BACKGROUND backgroundBonusSumContract(c),
                              bonusDebtSumContractDate BACKGROUND backgroundBonusSumContract(c)
    PROPERTIES(c, d) FORCE PANEL payContractDate, payPaymentConditionContractDate
    ORDER BY numberContract

    OBJECTS cl = contractLedger
    PROPERTIES(cl) READONLY dateContractLedger BACKGROUND backgroundContractLedgerDate(cl, d),
                            sumContractLedger BACKGROUND backgroundSumContractLedger(cl),
                            descriptionContractLedger BACKGROUND backgroundContractLedgerDate(cl, d)
    ORDER BY dateContractLedger

    OBJECTS cal = contractALedger
    PROPERTIES(cal) READONLY dateContractALedger BACKGROUND backgroundContractALedgerDate(cal, d),
                             sumContractALedger BACKGROUND backgroundSumContractALedger(cal),
                             descriptionContractALedger BACKGROUND backgroundContractALedgerDate(cal, d)
    ORDER BY dateContractALedger

    OBJECTS pm = payment
    PROPERTIES(pm) READONLY objectClassName BACKGROUND backgroundOutContractLedgerDate(pm, d),
                            dateTimePayment BACKGROUND backgroundOutContractLedgerDate(pm, d),
                            seriesNumberObject BACKGROUND backgroundOutContractLedgerDate(pm, d),
                            namePayerPayment BACKGROUND backgroundOutContractLedgerDate(pm, d),
                            nameBeneficiaryPayment BACKGROUND backgroundOutContractLedgerDate(pm, d),
                            nameCurrencyPayment BACKGROUND backgroundOutContractLedgerDate(pm, d),
                            nameTypeExchangePayment BACKGROUND backgroundOutContractLedgerDate(pm, d) SHOWIF isNotSameCurrencyPayment(pm),
                            sumPayment BACKGROUND backgroundOutContractLedgerDate(pm, d),
                            rateExchangePayment BACKGROUND backgroundOutContractLedgerDate(pm, d) SHOWIF isNotSameCurrencyPayment(pm),
                            sumRateExchangePayment BACKGROUND backgroundOutContractLedgerDate(pm, d) SHOWIF isNotSameCurrencyPayment(pm),
                            costedInContractLedgerOutContractLedger BACKGROUND backgroundOutContractLedgerDate(pm, d),
                            notePayment BACKGROUND backgroundOutContractLedgerDate(pm, d)
    PROPERTIES(pm) FORCE PANEL writeOutContractLedgerFIFO, writeOutContractLedgerLIFO
    PROPERTIES(pm) ADDFORM, EDITFORM, delete
    ORDER BY dateTimePayment

    OBJECTS pr = paymentRequest
    PROPERTIES(pr) READONLY objectClassName BACKGROUND backgroundPaymentRequestDate(pr, d),
                            dateTimePaymentRequest BACKGROUND backgroundPaymentRequestDate(pr, d),
                            seriesNumberObject BACKGROUND backgroundPaymentRequestDate(pr, d),
                            sumPaymentRequest BACKGROUND backgroundPaymentRequestDate(pr, d),
                            notePaymentRequest BACKGROUND backgroundPaymentRequestDate(pr, d)
    PROPERTIES(pr) ADDFORM, EDITFORM, delete
    ORDER BY dateTimePaymentRequest

    OBJECTS cm = creditMemo
    PROPERTIES(cm) READONLY objectClassName BACKGROUND backgroundOutContractLedgerDate(cm, d),
                            dateTimeCreditMemo BACKGROUND backgroundOutContractLedgerDate(cm, d),
                            seriesNumberObject BACKGROUND backgroundOutContractLedgerDate(cm, d),
                            sumCreditMemo BACKGROUND backgroundOutContractLedgerDate(cm, d),
                            noteCreditMemo BACKGROUND backgroundOutContractLedgerDate(cm, d)
    PROPERTIES(cm) FORCE GRID READONLY costedInContractLedgerOutContractLedger BACKGROUND backgroundOutContractLedgerDate(cm, d) SHOWIF isOutContractLedger(cm)
    PROPERTIES(cm) FORCE PANEL writeOutContractLedgerFIFO SHOWIF isOutContractLedger(cm),
                               writeOutContractLedgerLIFO SHOWIF isOutContractLedger(cm)
    PROPERTIES(cm) ADDFORM, EDITFORM, delete
    ORDER BY dateTimeCreditMemo


    OBJECTS ic = inContractLedger
    PROPERTIES(ic) READONLY descriptionInContractLedger, sumInContractLedger
    PROPERTIES(ic, d) READONLY debtInContractLedgerDate BACKGROUND backgroundBonusSumInContractLedger(ic),
                               bonusSumInContractLedger BACKGROUND backgroundBonusSumInContractLedger(ic),
                               bonusDebtSumInContractLedgerDate BACKGROUND backgroundBonusSumInContractLedger(ic)
    PROPERTIES(ic, d) FORCE PANEL payPaymentConditionInContractLedgerDate

    OBJECTS icoc = outContractLedger
    PROPERTIES(icoc) READONLY descriptionOutContractLedger, sumOutContractLedger
    PROPERTIES(icoc, d) READONLY costedInContractLedgerOutContractLedgerDate
    PROPERTIES READONLY costOutContractLedgerInContractLedger(icoc, ic)

    OBJECTS oc = outContractLedger
    PROPERTIES(oc) READONLY descriptionOutContractLedger, sumOutContractLedger
    PROPERTIES(oc, d) READONLY costedInContractLedgerOutContractLedgerDate
    PROPERTIES(oc) FORCE PANEL writeOutContractLedgerFIFO SHOWIF isOutContractLedger(oc),
                               writeOutContractLedgerLIFO SHOWIF isOutContractLedger(oc)

    OBJECTS ocic = inContractLedger
    PROPERTIES(ocic) READONLY descriptionInContractLedger, sumInContractLedger
    PROPERTIES(ocic, d) READONLY debtInContractLedgerDate
    PROPERTIES READONLY costOutContractLedgerInContractLedger(oc, ocic)

    FILTERS contractContractLedger(cl) == c,
            contractContractALedger(cal) == c,
            contractPayment(pm) == c,
            contractPaymentRequest(pr) == c,
            contractCreditMemo(cm) == c,
            contractInContractLedger(ic) == c,
            contractOutContractLedger(oc) == c,
            partyBContract(c) == partyB() OR (c IS contract AND NOT partyB()),
            partyAContract(c) == partyA() OR (c IS contract AND NOT partyA()),
            //dateContractLedger(cl) <= d,
            //dateContractALedger(cal) <= d,
            //datePayment(pm) <= d,
            //datePaymentRequest(pr) <= d,
            //dateCreditMemo(cm) <= d,
            //dateInContractLedger(ic) <=d,
            //dateOutContractLedger(oc) <=d,
            //dateInContractLedger(ocic) <=d,
            //dateOutContractLedger(icoc) <=d,
            costOutContractLedgerInContractLedger(icoc, ic) > 0,
            costOutContractLedgerInContractLedger(oc, ocic) > 0

;

DESIGN contractLedger FROM DEFAULT{

    NEW topContainer {

        childConstraints = TO THE BOTTOM;
        NEW headerContainer {
            childConstraints = TO THE RIGHT;
            caption = 'Шапка';
            ADD PROPERTY(date);
            ADD PROPERTY(namePartyA);
            ADD PROPERTY(namePartyB);
        }
        NEW firstContainer {

            type = SPLITV;
            ADD c.box{
                PROPERTY (payContractDate(c, d)){panelLocation = TOOLBAR;}
                PROPERTY (payPaymentConditionContractDate(c, d)){panelLocation = TOOLBAR;}
            }
            NEW firstSecondContainer {

                type = SPLITV;
                NEW firstThirdContainer {

                    type = SPLITH;
                    childConstraints = TO THE RIGHT;
                    ADD cl.box;
                    ADD cal.box;
                }
                NEW secondContainer {

                    type = TABBED;
                    ADD pm.box{
                         PROPERTY (writeOutContractLedgerFIFO(pm)){panelLocation = TOOLBAR;}
                         PROPERTY (writeOutContractLedgerLIFO(pm)){panelLocation = TOOLBAR;}
                    }
                    ADD pr.box;
                    ADD cm.box{
                        PROPERTY (writeOutContractLedgerFIFO(cm)){panelLocation = TOOLBAR;}
                        PROPERTY (writeOutContractLedgerLIFO(cm)){panelLocation = TOOLBAR;}
                    }
                    NEW debt.box{

                        childConstraints = TO THE RIGHT;
                        caption = 'Долг по документу';
                        ADD ic.box{
                            PROPERTY (payPaymentConditionInContractLedgerDate(ic, d)){panelLocation = TOOLBAR;}
                        }
                        ADD icoc.box;
                    }
                    NEW cost.box{

                        childConstraints = TO THE RIGHT;
                        caption = 'Расписано по документу';
                        ADD oc.box{
                            PROPERTY (writeOutContractLedgerFIFO(oc)){panelLocation = TOOLBAR;}
                            PROPERTY (writeOutContractLedgerLIFO(oc)){panelLocation = TOOLBAR;}
                        }
                        ADD ocic.box;
                    }
                }
            }
        }
    }

    ADD functions.box;
}