MODULE FiscalDatecs;

REQUIRE System,
        POS;

fiscalDatecsPrintReceipt 'Напечатать фискальный чек' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsPrintReceiptActionProperty';
postPrintReceipt(receipt) += fiscalDatecsPrintReceipt(receipt) IF sidCashRegisterModelReceipt(receipt) == 'DateCS';

fiscalDatecsAdvancePaper 'Прогон ленты' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsAdvancePaperActionProperty';
fiscalAdvancePaper() += fiscalDatecsAdvancePaper() IF sidModelCurrentCashRegister() == 'DateCS';

fiscalDatecsCutReceipt 'Отрезать чек' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsCutReceiptActionProperty';
fiscalCutReceipt() += fiscalDatecsCutReceipt() IF sidModelCurrentCashRegister() == 'DateCS';

fiscalDatecsXReport 'X-отчёт' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsXReportActionProperty';
fiscalXReport() += fiscalDatecsXReport() IF sidModelCurrentCashRegister() == 'DateCS';

fiscalDatecsZReport 'Z-отчёт' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsZReportActionProperty';
fiscalZReport() += fiscalDatecsZReport() IF sidModelCurrentCashRegister() == 'DateCS';

fiscalDatecsUpdateData 'Загрузить информацию' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsUpdateDataActionProperty';
fiscalUpdateData() += fiscalDatecsUpdateData() IF sidModelCurrentCashRegister() == 'DateCS';

fiscalDatecsServiceCashOperation 'Перемещение денег' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsServiceInOutActionProperty';
fiscalServiceCashOperation(cashOperation) += fiscalDatecsServiceCashOperation(cashOperation) IF sidCashRegisterModelCashOperation(cashOperation) == 'DateCS';

fiscalDatecsDisplayTextReceiptDetail 'Вывести текст на дисплей' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsDisplayTextActionProperty';
fiscalDisplayTextReceiptDetail (receiptDetail) += fiscalDatecsDisplayTextReceiptDetail(receiptDetail) IF sidCashRegisterModelReceiptDetail(receiptDetail) == 'DateCS';

fiscalDatecsCancelReceipt 'Отменить чек' = ACTION CUSTOM 'platform.fdk.actions.fiscaldatecs.FiscalDatecsCancelReceiptActionProperty';
fiscalCancelReceipt() += fiscalDatecsCancelReceipt() IF sidModelCurrentCashRegister() == 'DateCS';