MODULE PurchaseReturnInvoice;

REQUIRE Invoice,PurchaseReturnOrder;

NAMESPACE PurchaseReturn;

//----------------------------------------------- Накладная ---------------------------------------------------//

@defineInvoice(' (покупка-возврат)', supplier, supplier, company);
@defineInvoiceBatch();
@defineInvoiceReturn(Purchase, PurchaseReturn, supplier);

@defineInvoiceConsignment(company, supplier);
