MODULE Purchase;

REQUIRE PurchaseShipment, PurchaseReturnShipment, PurchaseCreditNote, PurchaseReturnCreditNote
;

//-----------------------------------------------------------------------------------------------------------//


currentReservePurchaseSkuStock 'Текущий резерв'(sku, stock)  = Purchase.currentReserveSkuStock(sku, stock) (-)
    PurchaseReturn.currentReserveSkuStock(sku, stock);

NAVIGATOR {

    NEW purchasePurchaseNavigator 'Закупки' {
        ADD Purchase.orders;
        ADD Purchase.invoices;
        ADD Purchase.shipments;
        ADD Purchase.creditNotes;
    }
    NEW purchaseReturnNavigator 'Возвраты' {
        ADD PurchaseReturn.orders;
        ADD PurchaseReturn.invoices;
        ADD PurchaseReturn.shipments;
        ADD PurchaseReturn.creditNotes;
    }
}



META defineDialogSkuPurchaseReserve (form)

    form###PurchaseReserve 'Резерв (закупки)' (sku) = currentReservePurchaseSkuStock(sku, form###stock());

    EXTEND FORM form
        PROPERTIES(s) READONLY form###PurchaseReserve AFTER form###balance SHOWIF form###stock()
    ;
END

@defineDialogSkuPurchaseReserve(dialogSku);