MODULE PurchaseReturnPricing;

REQUIRE Pricing, PurchaseReturnInvoice;

NAMESPACE PurchaseReturn;

// ------------------------------------- Автоматическое создание расценки для документа -------------------- //

@definePricingAggregation(return, ' (покупка-возврат)', 'Акт расценки при возврате', supplier, 'Поставщик');

//-- аггр.объект

retailMarkupUserInvoiceDetail(userInvoiceDetail)  <- [round2((((X - X*Y/(100+Y))/Z)-1)*100)](
    0.0 IF userInvoiceDetail IS userInvoiceDetail OR retailPriceUserInvoiceDetail(userInvoiceDetail),
    0.0 IF userInvoiceDetail IS userInvoiceDetail OR valueRetailVATUserInvoiceDetail(userInvoiceDetail),
    priceUserInvoiceDetail(userInvoiceDetail))
    WHEN CHANGED(retailPriceUserInvoiceDetail(userInvoiceDetail)) OR CHANGED (retailVATUserInvoiceDetail(userInvoiceDetail)) OR CHANGED(priceUserInvoiceDetail(userInvoiceDetail));

@derivePrevPriceLedgerOnSkuChangePrefix(retailPrice, userInvoice, retailPrice, sku, stock);
@derivePrevPriceLedgerOnSkuChangePrefix(retailVAT, userInvoice, retailVAT, sku, stock);

skipChangeLedgerPricing(pricing) +=  pricing IS returnPricing;
//--

