MODULE PurchaseReturnShipment;

REQUIRE Shipment, PurchaseReturnInvoice
;

NAMESPACE PurchaseReturn;


//----------------------------------------------- Поставка ---------------------------------------------------//

@defineShipment(outFIFOSkuLedger, ' (покупка-возврат)', supplier, 'Поставщик', supplier, company);
@defineShipmentBatch();

// Проводим по регистру

@implementSkuLedger(shipment, sku, stock);
quantityOutFIFOSkuLedger (ledger) += quantityShipmentDetail(ledger);
sumOutSkuLedger (ledger) += sumShipmentDetail(ledger);