MODULE PurchaseScheduleOrder;

REQUIRE PurchaseOrder,
        ScheduleOrder;

NAMESPACE Purchase;

@defineScheduleOrder(' (покупка)', purchase);

CONSTRAINT supplierScheduleOrder(scheduleOrder) AND NOT isCompanyLegalEntity(supplierScheduleOrder(scheduleOrder))
    CHECKED BY supplierScheduleOrder MESSAGE 'Для заказа выбрано в качестве поставщика организация, не являющаяся компанией';
CONSTRAINT customerScheduleOrder(scheduleOrder) AND NOT isCustomerLegalEntity(customerScheduleOrder(scheduleOrder))
    CHECKED BY customerScheduleOrder MESSAGE 'Для заказа выбрано в качестве покупателя организация, не являющаяся покупателем';

//CONSTRAINT supplier() AND NOT isSupplierLegalEntity(supplier())
//    CHECKED BY supplier MESSAGE 'Выбрана в качестве поставщика организация, не являющаяся поставщиком';
//CONSTRAINT customer() AND NOT isCompanyLegalEntity(customer())
//    CHECKED BY customer MESSAGE 'Выбрана в качестве покупателя организация, не являющаяся компанией';


EXTEND FORM legalEntity
    PROPERTIES(s, l) addScheduleOrderSupplierCustomer TODRAW ss
;


