MODULE PurchasePricing;

REQUIRE Pricing, PurchaseInvoice, Repricing;//, PurchaseShipment, StorePrice;

NAMESPACE Purchase;


//----------------------------------------------- Акт расценки ---------------------------------------------------//

@definePricing(' (покупка)', supplier, 'Поставщик');
@defineRepricing(' (покупка)');
//@implementSkuDepartmentStoreLedgerCustom(supplierPrice, pricing, sku, stock, price);
//@implementSkuDepartmentStoreLedger(retailVAT, pricing, sku, stock);
//@implementSkuDepartmentStoreLedger(retailPrice, pricing, sku, stock);
//
//overShipmentPriceUserInvoiceDetail(detail) += retailPriceUserInvoiceDetail(detail)
//    IF stockUserInvoiceDetail(detail) IS departmentStore AND NOT costLedgerDepartmentStore(stockUserInvoiceDetail(detail));
