MODULE SaleReturnShipment;

REQUIRE Shipment, SaleReturnInvoice
;

NAMESPACE SaleReturn;


//----------------------------------------------- Поставка ---------------------------------------------------//

@defineShipment(' (продажа-возврат)', customer, 'Покупатель', company, customer);
@defineShipmentBatch();

// Берем учетную цену
@deriveDocumentDetailPriceBatchStockPrefix(userInvoice, shipment);
@deriveDocumentDetailPriceBatchStock(userShipment);

// Проводим по регистру
@implementSkuLedgerInLIFO(shipment, sku, stock);
quantityInLIFOSkuLedger (ledger) += quantityShipmentDetail(ledger);
@implementSkuLedgerInLIFOBalance(shipment, sku, stock);
changedDataSkuLedger(ledger) += CHANGED(batchShipmentDetail(ledger));
sumInSkuLedger(ledger) += sumShipmentDetail(ledger);