MODULE SaleShipment;

REQUIRE Shipment, SaleInvoice;

NAMESPACE Sale;


//----------------------------------------------- Поставка ---------------------------------------------------//

@defineShipment(' (продажа)', customer, 'Покупатель', legalEntity, customer);
@defineShipmentBatch();

// Берем учетную цену
@deriveDocumentDetailPriceBatchStockPrefix(userInvoice, shipment);
@deriveDocumentDetailPriceBatchStock(userShipment);

// Проводим по регистру
@implementSkuLedgerOutFIFO(shipment, sku, stock);
quantityOutFIFOSkuLedger (ledger) += quantityShipmentDetail (ledger);
limitOutFIFOSkuLedgerBatch(ledger, batch) += IF batchShipmentDetail(ledger) THEN
                                                quantityShipmentDetail (ledger) AND batchShipmentDetail(ledger) == batch
                                                ELSE currentBalanceBatchStock(batch, stockShipmentDetail(ledger)); //AND NOT commissionContractSkuBatchA(batch);
changedDataSkuLedger(ledger) += CHANGED(batchShipmentDetail(ledger));
sumOutSkuLedger(ledger) += sumShipmentDetail(ledger);

@defineConstraintSkuLedgerCosted(shipment, 'Не хватает остатков по партиям для продажи товаров');

@implementAccountDocumentLedgerOut(shipment, stock);
sumOutAccountDocumentLedger (ledger) += sumShipmentDetailShipment(ledger);
sumItemOutAccountDocumentLedger (ledger) += sumItemShipmentDetailShipment(ledger);
sumContainerOutAccountDocumentLedger (ledger) += sumContainerShipmentDetailShipment(ledger);