MODULE Sale;

REQUIRE SaleShipment, SaleReturnShipment
;

//-----------------------------------------------------------------------------------------------------------//


currentReserveSaleSkuStock 'Текущий резерв'(sku, stock)  = Sale.currentReserveSkuStock(sku, stock) (-)
    SaleReturn.currentReserveSkuStock(sku, stock);

NAVIGATOR {
    NEW saleNavigator 'Продажи' {
        NEW saleSaleNavigator 'Управление продажами' {
            ADD Sale.userOrders;
            ADD Sale.userInvoices;
            ADD Sale.userShipments;
    //      ADD dialogShipments;
        }
        NEW saleReturnNavigator 'Управление возвратами' {
            ADD SaleReturn.userOrders;
            ADD SaleReturn.userInvoices;
            ADD SaleReturn.userShipments;
    //      ADD dialogShipments;
        }
    }
}


META defineDialogSkuReserve (form)

    form###reserve 'Резерв' (sku) = currentReserveSaleSkuStock(sku, form###stock());

    EXTEND FORM form
        PROPERTIES(s) READONLY  form###reserve AFTER form###balance SHOWIF form###stock()
    ;
END

@defineDialogSkuReserve(dialogSku);




