MODULE PurchaseInvoicePharmacy;

REQUIRE System, PurchaseInvoice;

NAMESPACE Purchase;

seriesPharmacyInvoiceDetail 'Серия лекарственного средства' = ABSTRACT STRING[100] (InvoiceDetail) MINCHARWIDTH 20 PREFCHARWIDTH 40;

seriesPharmacyUserInvoiceDetail 'Серия лекарственного средства' = DATA STRING[100] (UserInvoiceDetail) MINCHARWIDTH 20 PREFCHARWIDTH 40;

showSeriesPharmacy 'Показывать серию лекарственного средства' = DATA BOOLEAN ();

EXTEND FORM options
    PROPERTIES() showSeriesPharmacy
;

EXTEND DESIGN options {
    commons {
        ADD PROPERTY(showSeriesPharmacy);
    }
}

seriesPharmacyInvoiceDetail(detail) += seriesPharmacyUserInvoiceDetail(detail);

EXTEND FORM userInvoice
    PROPERTIES(d) seriesPharmacyUserInvoiceDetail SHOWIF showSeriesPharmacy() BEFORE nameBatchUserInvoiceDetail
;

EXTEND FORM invoices
    PROPERTIES(d) READONLY seriesPharmacyInvoiceDetail SHOWIF showSeriesPharmacy() BEFORE nameBatchInvoiceDetail
;
