MODULE InvoiceConsignmentBy;

REQUIRE Invoice,
        ConsignmentBy;

NAMESPACE Invoice;

META defineInvoiceConsignment(contactA, contactB)
    @defineConsignmentInterfaceHeader(invoice);
    @implementConsignmentInterfaceHeader(invoice);

    supplierConsignment (consignment) += contactA###invoice(consignment);
    supplierStockConsignment (consignment) += contactA###stock###invoice(consignment);

    customerConsignment (consignment) += contactB###invoice(consignment);
    customerStockConsignment (consignment) += contactB###stock###invoice(consignment);

    currencyConsignment (consignment) += currencyInvoice(consignment);

    @implementConsignmentDetail(invoice);

    priceConsignmentDetail (consignmentDetail) += priceInvoiceDetail(consignmentDetail);
    sumConsignmentDetail (consignmentDetail) += sumInvoiceDetail (consignmentDetail);
    vatConsignmentDetail (consignmentDetail) += valueVATInvoiceDetail(consignmentDetail);
    sumVATConsignmentDetail (consignmentDetail) +=  VATSumInvoiceDetail(consignmentDetail);
    sumInvoiceConsignmentDetail (consignmentDetail) += invoiceSumInvoiceDetail(consignmentDetail);
    shortNameUOMConsignmentDetail (consignmentDetail) += shortNameUOMSku(skuInvoiceDetail (consignmentDetail));

    EXTEND FORM  invoices
        PROPERTIES (i)  FORCE PANEL printConsignmentVerticalA, printConsignmentHorizontalA,
                         printConsignmentVerticalB, printConsignmentHorizontalB,
                         printConsignmentAttach, printConsignmentSimpleHorizontal, editConsignment,
                         printConsignmentSimpleVertical, printConsignmentSimpleAttach
    ;

    EXTEND DESIGN invoices {
        printContainer {
            NEW consignmentRow1 {
                childConstraints = TO THE RIGHT;

                NEW contOne {
                    title = 'Накладная';
                    ADD PROPERTY(editConsignment);
                }
                NEW tn{
                    childConstraints = TO THE RIGHT;
                    title = 'ТН-2';
                    ADD PROPERTY(printConsignmentSimpleVertical);
                    ADD PROPERTY(printConsignmentSimpleHorizontal);
                    ADD PROPERTY(printConsignmentSimpleAttach);
                }
            }
            NEW consignmentRow2 {
                childConstraints = TO THE RIGHT;
                title = 'ТТН-1';
                ADD PROPERTY(printConsignmentVerticalA);
                ADD PROPERTY(printConsignmentHorizontalA);
                ADD PROPERTY(printConsignmentVerticalB);
                ADD PROPERTY(printConsignmentHorizontalB);
                ADD PROPERTY(printConsignmentAttach);
            }
        }
    }
END