package lsfusion.interop.classes;

public class DataType {

    public final static byte OBJECT = 0;
    public final static byte INTEGER = 1;
    public final static byte LONG = 2;
    public final static byte DOUBLE = 3;
    public final static byte NUMERIC = 4;
    public final static byte LOGICAL = 5;
    public final static byte ACTION = 6;
    public final static byte DATE = 7;
    public final static byte STRING = 8;
    public final static byte BYTEARRAY = 9;
    public final static byte BIT = 10;
    public final static byte CUSTOMSTATICFORMATFILE = 12;
    public final static byte IMAGE = 13;
    public final static byte WORD = 14;
    public final static byte EXCEL = 15;
    public final static byte TEXT = 16;
    public final static byte YEAR = 17;
    public final static byte INSENSITIVESTRING = 18;
    public final static byte PDF = 19;
    public final static byte DATETIME = 20;
    public final static byte DYNAMICFORMATFILE = 21;
    public final static byte TIME = 22;
    public final static byte COLOR = 23;
    public final static byte PDFLINK = 25;
    public final static byte IMAGELINK = 26;
    public final static byte WORDLINK = 27;
    public final static byte EXCELLINK = 28;
    public final static byte DYNAMICFORMATLINK = 29;
    public final static byte CUSTOMSTATICFORMATLINK = 30;
    public final static byte CSV = 31;
    public final static byte CSVLINK = 32;
    public final static byte HTML = 33;
    public final static byte HTMLLINK = 34;
    public final static byte JSON = 35;
    public final static byte JSONLINK = 36;
    public final static byte XML = 37;
    public final static byte XMLLINK = 38;
    public final static byte TABLE = 39;
    public final static byte TABLELINK = 40;
    public final static byte TXT = 41;
    public final static byte TXTLINK = 42;
    public final static byte ZDATETIME = 43;
    public final static byte JDBC = 44;
    public final static byte DATEINTERVAL = 45;
    public final static byte DATETIMEINTERVAL = 46;
    public final static byte TIMEINTERVAL = 47;
    public final static byte DBF = 48;
    public final static byte DBFLINK = 49;
}
