MODULE OrderBy;

REQUIRE LegalEntityBy, Bank, Order;

NAMESPACE Order;

@defineDocumentUNPLegalEntity(order, supplier, ' поставщика');
@defineDocumentUNPLegalEntity(order, customer, ' покупателя');

@defineDocumentAccount(order, supplier, ' поставщика');
@defineDocumentPhone(order, supplier, ' поставщика');

@defineDocumentAccount(order, customer, ' покупателя');
@defineDocumentPhone(order, customer, ' покупателя');

FORM printOrderBy 'Счет-фактура (печать)' PRINT
    OBJECTS o = Order FIXED PANEL
    PROPERTIES (o) READONLY nameSupplierOrder, nameSupplierStockOrder, addressSupplierOrder, UNPSupplierOrder,
                   numberAccountSupplierOrder, nameBankSupplierOrder, addressBankSupplierOrder,
                   departmentBankSupplierOrder, CBUBankSupplierOrder, MFOBankSupplierOrder, phoneSupplierOrder,
                   nameCustomerOrder, nameCustomerStockOrder, addressCustomerOrder, UNPCustomerOrder,
                   numberAccountCustomerOrder, nameBankCustomerOrder, addressBankCustomerOrder,
                   departmentBankCustomerOrder, CBUBankCustomerOrder, MFOBankCustomerOrder, phoneCustomerOrder,
                   numberOrder, seriesOrder, seriesNumberOrder, dateOrder, timeOrder, closeDateOrder, currencyOrder,
                   nameCurrencyOrder, noteOrder, countOrderDetailOrder, quantityOrderDetailOrder, sumOrderDetailOrder,
                   VATSumOrderDetailOrder, invoiceSumOrderDetailOrder

    OBJECTS d = OrderDetail
    PROPERTIES (d) READONLY indexOrderDetail, nameSkuOrderDetail, shortNameUOMSkuOrderDetail,
                   quantityOrderDetail,
                   priceOrderDetail, sumOrderDetail, numberVATOrderDetail,
                   valueVATOrderDetail,  VATSumOrderDetail, invoiceSumOrderDetail
    FILTERS orderOrderDetail(d) == o
;

printOrderBy 'Счет-фактура' (order) = ACTION FORM printOrderBy OBJECTS o = order IMAGE 'print.png' IN printGroup;
