MODULE Scheduler;

REQUIRE System, Reflection, Service;


CLASS SchedulerStartType 'Отсчёт времени' {
    afterStart 'От запуска предыдущего',
    afterFinish 'От окончания предыдущего'
}

FORM schedulerStartTypes 'Способ отсчета времени'
    OBJECTS s = SchedulerStartType
    PROPERTIES(s) READONLY staticCaption
    DIALOG SchedulerStartType OBJECT s
;

EXTEND DESIGN schedulerStartTypes {
    main {
        PROPERTY(staticCaption(s)) {
            caption = 'Отсчёт времени';
        }
    }
}

CLASS ScheduledTask 'Задание планировщика';
TABLE scheduledTask (ScheduledTask);

nameScheduledTask 'Имя' = DATA VARSTRING[100] (ScheduledTask);
scheduledTaskName (name) = GROUP AGGR task BY nameScheduledTask(task) WHERE task IS ScheduledTask;

runAtStartScheduledTask 'Выполнить при старте' = DATA BOOLEAN (ScheduledTask);
startDateScheduledTask 'Дата начала' = DATA DATETIME (ScheduledTask);
periodScheduledTask 'Повторять каждые (секунд)' = DATA INTEGER (ScheduledTask);
schedulerStartTypeScheduledTask 'Отсчёт времени' = DATA SchedulerStartType (ScheduledTask);
nameSchedulerStartTypeScheduledTask 'Отсчёт времени' = staticCaption(schedulerStartTypeScheduledTask(ScheduledTask));
activeScheduledTask 'Активно' = DATA BOOLEAN (ScheduledTask);

CLASS ScheduledTaskDetail 'Строка задания планировщика';
TABLE scheduledTaskDetail (ScheduledTaskDetail);

activeScheduledTaskDetail 'Активно' = DATA BOOLEAN (ScheduledTaskDetail);
orderScheduledTaskDetail 'Порядок' = DATA INTEGER (ScheduledTaskDetail);

scheduledTaskScheduledTaskDetail = DATA ScheduledTask (ScheduledTaskDetail) NOT NULL DELETE;
propertyScheduledTaskDetail = DATA Property (ScheduledTaskDetail);
captionPropertyScheduledTaskDetail 'Свойство' (scheduledTaskDetail) = captionProperty(propertyScheduledTaskDetail(scheduledTaskDetail));
canonicalNamePropertyScheduledTaskDetail 'Код свойства' (scheduledTaskDetail) = canonicalNameProperty(propertyScheduledTaskDetail(scheduledTaskDetail));
classPropertyScheduledTaskDetail 'Класс свойства' (scheduledTaskDetail) = classProperty(propertyScheduledTaskDetail(scheduledTaskDetail));
returnPropertyScheduledTaskDetail 'Возвращаемый класс' (scheduledTaskDetail) = returnProperty(propertyScheduledTaskDetail(scheduledTaskDetail));
signaturePropertyScheduledTaskDetail 'Сигнатура' (scheduledTaskDetail) = signatureProperty(propertyScheduledTaskDetail(scheduledTaskDetail));

CLASS ScheduledTaskLog 'Лог планировщика';
TABLE scheduledTaskLog (ScheduledTaskLog);
TABLE scheduledTaskScheduledTaskLog (ScheduledTask, ScheduledTaskLog);

resultScheduledTaskLog 'Результат' = DATA VARSTRING[200] (ScheduledTaskLog);
propertyScheduledTaskLog 'Свойство' = DATA VARSTRING[200] (ScheduledTaskLog);
dateScheduledTaskLog 'Время' = DATA DATETIME (ScheduledTaskLog);
toDateScheduledTaskLog 'Дата' (d) = DATE(dateScheduledTaskLog(d));
scheduledTaskScheduledTaskLog 'Задание планировщика' = DATA ScheduledTask (ScheduledTaskLog);

@defineLog (ScheduledTaskLog, 'планировщика', log, toDate);

CLASS ScheduledClientTaskLog 'Сообщения клиента';
TABLE scheduledClientTaskLog (ScheduledClientTaskLog);

scheduledTaskLogScheduledClientTaskLog 'Лог планировщика'= DATA ScheduledTaskLog (ScheduledClientTaskLog) NOT NULL DELETE;
messageScheduledClientTaskLog 'Сообщение'= DATA TEXT (ScheduledClientTaskLog);

runSetupScheduler 'Планировщик' = ACTION CUSTOM 'lsfusion.server.SetupSchedulerActionProperty' ();

WHEN ((CHANGED (runAtStartScheduledTask(t)) OR CHANGED (startDateScheduledTask(t)) OR CHANGED (periodScheduledTask(t)) 
    OR CHANGED (schedulerStartTypeScheduledTask(t)) OR CHANGED (schedulerStartTypeScheduledTask(t))) AND activeScheduledTask(t)
    OR CHANGED (activeScheduledTask(t)))
 DO EXEC runSetupScheduler();
 
 WHEN ((CHANGED (activeScheduledTaskDetail(td)) OR CHANGED (orderScheduledTaskDetail(td)) 
    OR CHANGED (scheduledTaskScheduledTaskDetail(td)) OR CHANGED (propertyScheduledTaskDetail(td))) AND activeScheduledTask(scheduledTaskScheduledTaskDetail(td)))
  DO EXEC runSetupScheduler();
           
FORM scheduledTask 'Планировщик'

    OBJECTS t=ScheduledTask
    PROPERTIES (t) activeScheduledTask, nameScheduledTask, startDateScheduledTask, periodScheduledTask,
                    nameSchedulerStartTypeScheduledTask, runAtStartScheduledTask
    PROPERTIES (t) ADDOBJ, DELETESESSION
         
    OBJECTS td=ScheduledTaskDetail
    PROPERTIES (td) activeScheduledTaskDetail, orderScheduledTaskDetail, captionPropertyScheduledTaskDetail, 
                    canonicalNamePropertyScheduledTaskDetail, classPropertyScheduledTaskDetail, returnPropertyScheduledTaskDetail
    PROPERTIES (td) ADDOBJ, DELETESESSION
    
    OBJECTS tl=ScheduledTaskLog
    PROPERTIES (tl) READONLY propertyScheduledTaskLog, resultScheduledTaskLog, dateScheduledTaskLog

    OBJECTS ctl=ScheduledClientTaskLog
    PROPERTIES (ctl) READONLY messageScheduledClientTaskLog

    FILTERS scheduledTaskScheduledTaskDetail(td)==t,
            scheduledTaskScheduledTaskLog(tl) == t,
            scheduledTaskLogScheduledClientTaskLog(ctl) == tl

    FILTERGROUP filtersScheduler
            FILTER 'Только активные' activeScheduledTaskDetail(td) 'F9'
;

EXTEND DESIGN scheduledTask {
    NEW specContainer {
        fill = 1; 
        type = SPLITV;
        ADD t.box;
        NEW south {
            fill = 2;
            type = TABBED;
            ADD td.box {caption = 'Свойства';}
            NEW logContainer {
                caption = 'Лог';
                type = CONTAINERH;
                ADD tl.box;
                ADD ctl.box;
            }
        }
    }
    ADD functions.box;
}

FORM scheduledTaskProperties 'Свойства'
    OBJECTS p = Property
    PROPERTIES(p) READONLY captionProperty, canonicalNameProperty, classProperty, returnProperty
    FILTERS signatureProperty(p) == '',
            returnProperty(p) == 'ActionClass'
;

NAVIGATOR {
    configuration {
        ADD Scheduler.scheduledTask;
    }
}